// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.1 (64-bit)
// Version: 2022.1
// Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module ISPPipeline_accel_xfccmkernel_17_1080_1920_21_1_11_11_1920_2_Pipeline_colLoop (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        ltm_in_data242_dout,
        ltm_in_data242_num_data_valid,
        ltm_in_data242_fifo_cap,
        ltm_in_data242_empty_n,
        ltm_in_data242_read,
        lsc_out_data243_din,
        lsc_out_data243_num_data_valid,
        lsc_out_data243_fifo_cap,
        lsc_out_data243_full_n,
        lsc_out_data243_write,
        width
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [29:0] ltm_in_data242_dout;
input  [1:0] ltm_in_data242_num_data_valid;
input  [1:0] ltm_in_data242_fifo_cap;
input   ltm_in_data242_empty_n;
output   ltm_in_data242_read;
output  [29:0] lsc_out_data243_din;
input  [1:0] lsc_out_data243_num_data_valid;
input  [1:0] lsc_out_data243_fifo_cap;
input   lsc_out_data243_full_n;
output   lsc_out_data243_write;
input  [10:0] width;

reg ap_idle;
reg ltm_in_data242_read;
reg lsc_out_data243_write;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_enable_reg_pp0_iter3;
reg    ap_enable_reg_pp0_iter4;
reg    ap_enable_reg_pp0_iter5;
reg    ap_enable_reg_pp0_iter6;
reg    ap_enable_reg_pp0_iter7;
reg    ap_idle_pp0;
wire    ap_block_state1_pp0_stage0_iter0;
reg    ap_block_state2_pp0_stage0_iter1;
wire    ap_block_state3_pp0_stage0_iter2;
wire    ap_block_state4_pp0_stage0_iter3;
wire    ap_block_state5_pp0_stage0_iter4;
wire    ap_block_state6_pp0_stage0_iter5;
wire    ap_block_state7_pp0_stage0_iter6;
reg    ap_block_state8_pp0_stage0_iter7;
reg    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln245_fu_145_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
reg    ltm_in_data242_blk_n;
wire    ap_block_pp0_stage0;
reg    lsc_out_data243_blk_n;
reg    ap_block_pp0_stage0_11001;
wire   [9:0] r_V_fu_162_p1;
reg   [9:0] r_V_reg_777;
wire   [9:0] g_V_fu_166_p4;
reg   [9:0] g_V_reg_782;
wire   [9:0] b_V_fu_176_p4;
reg   [9:0] b_V_reg_787;
reg   [9:0] b_V_reg_787_pp0_iter2_reg;
wire   [38:0] zext_ln1316_4_fu_215_p1;
reg   [18:0] tmp_3_reg_828;
reg   [18:0] tmp_6_reg_833;
reg   [18:0] tmp_10_reg_843;
reg   [15:0] tmp_8_reg_848;
reg   [12:0] tmp_11_reg_853;
reg   [18:0] tmp_14_reg_858;
wire   [20:0] ret_V_12_fu_330_p2;
reg   [20:0] ret_V_12_reg_863;
wire   [20:0] ret_V_15_fu_343_p2;
reg   [20:0] ret_V_15_reg_868;
wire   [20:0] ret_V_18_fu_357_p2;
reg   [20:0] ret_V_18_reg_873;
wire  signed [14:0] ret_V_14_fu_429_p3;
reg  signed [14:0] ret_V_14_reg_878;
wire  signed [14:0] ret_V_17_fu_503_p3;
reg  signed [14:0] ret_V_17_reg_883;
wire  signed [14:0] ret_V_20_fu_577_p3;
reg  signed [14:0] ret_V_20_reg_888;
reg   [4:0] tmp_18_reg_893;
reg   [4:0] tmp_20_reg_898;
reg   [4:0] tmp_22_reg_903;
wire   [9:0] select_ln260_fu_649_p3;
reg   [9:0] select_ln260_reg_908;
wire   [9:0] select_ln260_1_fu_682_p3;
reg   [9:0] select_ln260_1_reg_913;
wire   [9:0] select_ln260_2_fu_715_p3;
reg   [9:0] select_ln260_2_reg_918;
reg   [10:0] j_V_fu_114;
wire   [10:0] j_V_2_fu_151_p2;
wire    ap_loop_init;
reg   [10:0] ap_sig_allocacmp_j_V_1;
reg    ap_block_pp0_stage0_01001;
wire   [9:0] grp_fu_209_p0;
wire   [29:0] grp_fu_209_p1;
wire   [9:0] grp_fu_218_p0;
wire  signed [28:0] grp_fu_218_p1;
wire   [9:0] grp_fu_224_p0;
wire   [29:0] grp_fu_224_p1;
wire   [38:0] grp_fu_209_p2;
wire   [38:0] grp_fu_218_p2;
wire   [38:0] grp_fu_224_p2;
wire   [9:0] grp_fu_263_p0;
wire   [29:0] grp_fu_263_p1;
wire  signed [35:0] grp_fu_731_p2;
wire  signed [35:0] grp_fu_738_p2;
wire  signed [32:0] grp_fu_745_p2;
wire  signed [33:0] grp_fu_752_p2;
wire  signed [35:0] grp_fu_759_p2;
wire   [38:0] grp_fu_263_p2;
wire  signed [20:0] sext_ln1393_fu_327_p1;
wire   [20:0] zext_ln1393_fu_324_p1;
wire   [15:0] tmp_9_fu_278_p4;
wire   [20:0] zext_ln1393_1_fu_340_p1;
wire  signed [20:0] sext_ln1393_3_fu_336_p1;
wire   [13:0] tmp_12_fu_296_p4;
wire   [15:0] tmp_13_fu_305_p4;
wire  signed [20:0] sext_ln1393_7_fu_353_p1;
wire  signed [20:0] sext_ln1393_6_fu_349_p1;
wire  signed [21:0] sext_ln1393_1_fu_363_p1;
wire  signed [21:0] sext_ln1393_2_fu_366_p1;
wire   [21:0] ret_V_13_fu_369_p2;
wire   [13:0] tmp_1_fu_375_p4;
wire   [7:0] trunc_ln1049_fu_397_p1;
wire   [27:0] tmp_fu_401_p3;
wire  signed [14:0] sext_ln1048_fu_385_p1;
wire   [0:0] icmp_ln1049_fu_409_p2;
wire   [14:0] ret_V_fu_415_p2;
wire   [0:0] p_Result_s_fu_389_p3;
wire   [14:0] select_ln1048_fu_421_p3;
wire  signed [21:0] sext_ln1393_4_fu_437_p1;
wire  signed [21:0] sext_ln1393_5_fu_440_p1;
wire   [21:0] ret_V_16_fu_443_p2;
wire   [13:0] tmp_5_fu_449_p4;
wire   [7:0] trunc_ln1049_1_fu_471_p1;
wire   [27:0] tmp_2_fu_475_p3;
wire  signed [14:0] sext_ln1048_1_fu_459_p1;
wire   [0:0] icmp_ln1049_1_fu_483_p2;
wire   [14:0] ret_V_6_fu_489_p2;
wire   [0:0] p_Result_1_fu_463_p3;
wire   [14:0] select_ln1048_1_fu_495_p3;
wire  signed [21:0] sext_ln1393_8_fu_511_p1;
wire   [21:0] zext_ln1393_2_fu_514_p1;
wire   [21:0] ret_V_19_fu_517_p2;
wire   [13:0] tmp_7_fu_523_p4;
wire   [7:0] trunc_ln1049_2_fu_545_p1;
wire   [27:0] tmp_4_fu_549_p3;
wire  signed [14:0] sext_ln1048_2_fu_533_p1;
wire   [0:0] icmp_ln1049_2_fu_557_p2;
wire   [14:0] ret_V_10_fu_563_p2;
wire   [0:0] p_Result_2_fu_537_p3;
wire   [14:0] select_ln1048_2_fu_569_p3;
wire   [0:0] icmp_ln97_fu_624_p2;
wire  signed [15:0] sext_ln1029_fu_615_p1;
wire   [15:0] select_ln97_fu_629_p3;
wire   [0:0] tmp_19_fu_637_p3;
wire   [9:0] trunc_ln260_fu_645_p1;
wire   [0:0] icmp_ln97_1_fu_657_p2;
wire  signed [15:0] sext_ln1029_1_fu_618_p1;
wire   [15:0] select_ln97_1_fu_662_p3;
wire   [0:0] tmp_21_fu_670_p3;
wire   [9:0] trunc_ln260_1_fu_678_p1;
wire   [0:0] icmp_ln97_2_fu_690_p2;
wire  signed [15:0] sext_ln1029_2_fu_621_p1;
wire   [15:0] select_ln97_2_fu_695_p3;
wire   [0:0] tmp_23_fu_703_p3;
wire   [9:0] trunc_ln260_2_fu_711_p1;
wire   [9:0] grp_fu_731_p0;
wire  signed [25:0] grp_fu_731_p1;
wire   [9:0] grp_fu_738_p0;
wire  signed [25:0] grp_fu_738_p1;
wire   [9:0] grp_fu_745_p0;
wire  signed [22:0] grp_fu_745_p1;
wire   [9:0] grp_fu_752_p0;
wire  signed [23:0] grp_fu_752_p1;
wire   [9:0] grp_fu_759_p0;
wire  signed [25:0] grp_fu_759_p1;
reg    grp_fu_209_ce;
reg    grp_fu_218_ce;
reg    grp_fu_224_ce;
reg    grp_fu_263_ce;
reg    grp_fu_731_ce;
reg    grp_fu_738_ce;
reg    grp_fu_745_ce;
reg    grp_fu_752_ce;
reg    grp_fu_759_ce;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg    ap_loop_exit_ready_pp0_iter1_reg;
reg    ap_loop_exit_ready_pp0_iter2_reg;
reg    ap_loop_exit_ready_pp0_iter3_reg;
reg    ap_loop_exit_ready_pp0_iter4_reg;
reg    ap_loop_exit_ready_pp0_iter5_reg;
reg    ap_loop_exit_ready_pp0_iter6_reg;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire   [38:0] grp_fu_209_p00;
wire   [38:0] grp_fu_263_p00;
wire   [35:0] grp_fu_731_p00;
wire   [35:0] grp_fu_738_p00;
wire   [32:0] grp_fu_745_p00;
wire   [33:0] grp_fu_752_p00;
wire   [35:0] grp_fu_759_p00;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
#0 ap_enable_reg_pp0_iter4 = 1'b0;
#0 ap_enable_reg_pp0_iter5 = 1'b0;
#0 ap_enable_reg_pp0_iter6 = 1'b0;
#0 ap_enable_reg_pp0_iter7 = 1'b0;
#0 ap_done_reg = 1'b0;
end

ISPPipeline_accel_mul_10ns_30ns_39_2_1 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 10 ),
    .din1_WIDTH( 30 ),
    .dout_WIDTH( 39 ))
mul_10ns_30ns_39_2_1_U370(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_209_p0),
    .din1(grp_fu_209_p1),
    .ce(grp_fu_209_ce),
    .dout(grp_fu_209_p2)
);

ISPPipeline_accel_mul_10ns_29s_39_2_1 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 10 ),
    .din1_WIDTH( 29 ),
    .dout_WIDTH( 39 ))
mul_10ns_29s_39_2_1_U371(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_218_p0),
    .din1(grp_fu_218_p1),
    .ce(grp_fu_218_ce),
    .dout(grp_fu_218_p2)
);

ISPPipeline_accel_mul_10ns_30ns_39_2_1 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 10 ),
    .din1_WIDTH( 30 ),
    .dout_WIDTH( 39 ))
mul_10ns_30ns_39_2_1_U372(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_224_p0),
    .din1(grp_fu_224_p1),
    .ce(grp_fu_224_ce),
    .dout(grp_fu_224_p2)
);

ISPPipeline_accel_mul_10ns_30ns_39_2_1 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 10 ),
    .din1_WIDTH( 30 ),
    .dout_WIDTH( 39 ))
mul_10ns_30ns_39_2_1_U373(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_263_p0),
    .din1(grp_fu_263_p1),
    .ce(grp_fu_263_ce),
    .dout(grp_fu_263_p2)
);

ISPPipeline_accel_mul_mul_10ns_26s_36_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 10 ),
    .din1_WIDTH( 26 ),
    .dout_WIDTH( 36 ))
mul_mul_10ns_26s_36_4_1_U374(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_731_p0),
    .din1(grp_fu_731_p1),
    .ce(grp_fu_731_ce),
    .dout(grp_fu_731_p2)
);

ISPPipeline_accel_mul_mul_10ns_26s_36_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 10 ),
    .din1_WIDTH( 26 ),
    .dout_WIDTH( 36 ))
mul_mul_10ns_26s_36_4_1_U375(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_738_p0),
    .din1(grp_fu_738_p1),
    .ce(grp_fu_738_ce),
    .dout(grp_fu_738_p2)
);

ISPPipeline_accel_mul_mul_10ns_23s_33_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 10 ),
    .din1_WIDTH( 23 ),
    .dout_WIDTH( 33 ))
mul_mul_10ns_23s_33_4_1_U376(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_745_p0),
    .din1(grp_fu_745_p1),
    .ce(grp_fu_745_ce),
    .dout(grp_fu_745_p2)
);

ISPPipeline_accel_mul_mul_10ns_24s_34_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 10 ),
    .din1_WIDTH( 24 ),
    .dout_WIDTH( 34 ))
mul_mul_10ns_24s_34_4_1_U377(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_752_p0),
    .din1(grp_fu_752_p1),
    .ce(grp_fu_752_ce),
    .dout(grp_fu_752_p2)
);

ISPPipeline_accel_mul_mul_10ns_26s_36_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 10 ),
    .din1_WIDTH( 26 ),
    .dout_WIDTH( 36 ))
mul_mul_10ns_26s_36_4_1_U378(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_759_p0),
    .din1(grp_fu_759_p1),
    .ce(grp_fu_759_ce),
    .dout(grp_fu_759_p2)
);

ISPPipeline_accel_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter6_reg == 1'b1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter0_stage0)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter4 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter5 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter5 <= ap_enable_reg_pp0_iter4;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter6 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter6 <= ap_enable_reg_pp0_iter5;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter7 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter7 <= ap_enable_reg_pp0_iter6;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln245_fu_145_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            j_V_fu_114 <= j_V_2_fu_151_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            j_V_fu_114 <= 11'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
        ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready_pp0_iter1_reg;
        b_V_reg_787 <= {{ltm_in_data242_dout[29:20]}};
        g_V_reg_782 <= {{ltm_in_data242_dout[19:10]}};
        r_V_reg_777 <= r_V_fu_162_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        ap_loop_exit_ready_pp0_iter3_reg <= ap_loop_exit_ready_pp0_iter2_reg;
        ap_loop_exit_ready_pp0_iter4_reg <= ap_loop_exit_ready_pp0_iter3_reg;
        ap_loop_exit_ready_pp0_iter5_reg <= ap_loop_exit_ready_pp0_iter4_reg;
        ap_loop_exit_ready_pp0_iter6_reg <= ap_loop_exit_ready_pp0_iter5_reg;
        b_V_reg_787_pp0_iter2_reg <= b_V_reg_787;
        ret_V_12_reg_863 <= ret_V_12_fu_330_p2;
        ret_V_14_reg_878 <= ret_V_14_fu_429_p3;
        ret_V_15_reg_868 <= ret_V_15_fu_343_p2;
        ret_V_17_reg_883 <= ret_V_17_fu_503_p3;
        ret_V_18_reg_873 <= ret_V_18_fu_357_p2;
        ret_V_20_reg_888 <= ret_V_20_fu_577_p3;
        select_ln260_1_reg_913 <= select_ln260_1_fu_682_p3;
        select_ln260_2_reg_918 <= select_ln260_2_fu_715_p3;
        select_ln260_reg_908 <= select_ln260_fu_649_p3;
        tmp_10_reg_843 <= {{grp_fu_224_p2[38:20]}};
        tmp_11_reg_853 <= {{grp_fu_745_p2[32:20]}};
        tmp_14_reg_858 <= {{grp_fu_263_p2[38:20]}};
        tmp_18_reg_893 <= {{ret_V_14_fu_429_p3[14:10]}};
        tmp_20_reg_898 <= {{ret_V_17_fu_503_p3[14:10]}};
        tmp_22_reg_903 <= {{ret_V_20_fu_577_p3[14:10]}};
        tmp_3_reg_828 <= {{grp_fu_209_p2[38:20]}};
        tmp_6_reg_833 <= {{grp_fu_218_p2[38:20]}};
        tmp_8_reg_848 <= {{grp_fu_731_p2[35:20]}};
    end
end

always @ (*) begin
    if (((icmp_ln245_fu_145_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter6_reg == 1'b1))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b0) & (ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter7 == 1'b0) & (ap_enable_reg_pp0_iter6 == 1'b0) & (ap_enable_reg_pp0_iter5 == 1'b0) & (ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
        ap_sig_allocacmp_j_V_1 = 11'd0;
    end else begin
        ap_sig_allocacmp_j_V_1 = j_V_fu_114;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_fu_209_ce = 1'b1;
    end else begin
        grp_fu_209_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_fu_218_ce = 1'b1;
    end else begin
        grp_fu_218_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_fu_224_ce = 1'b1;
    end else begin
        grp_fu_224_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_fu_263_ce = 1'b1;
    end else begin
        grp_fu_263_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_fu_731_ce = 1'b1;
    end else begin
        grp_fu_731_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_fu_738_ce = 1'b1;
    end else begin
        grp_fu_738_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_fu_745_ce = 1'b1;
    end else begin
        grp_fu_745_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_fu_752_ce = 1'b1;
    end else begin
        grp_fu_752_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_fu_759_ce = 1'b1;
    end else begin
        grp_fu_759_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter7 == 1'b1))) begin
        lsc_out_data243_blk_n = lsc_out_data243_full_n;
    end else begin
        lsc_out_data243_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter7 == 1'b1))) begin
        lsc_out_data243_write = 1'b1;
    end else begin
        lsc_out_data243_write = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ltm_in_data242_blk_n = ltm_in_data242_empty_n;
    end else begin
        ltm_in_data242_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ltm_in_data242_read = 1'b1;
    end else begin
        ltm_in_data242_read = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_01001 = (((lsc_out_data243_full_n == 1'b0) & (ap_enable_reg_pp0_iter7 == 1'b1)) | ((ltm_in_data242_empty_n == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b1)));
end

always @ (*) begin
    ap_block_pp0_stage0_11001 = (((lsc_out_data243_full_n == 1'b0) & (ap_enable_reg_pp0_iter7 == 1'b1)) | ((ltm_in_data242_empty_n == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b1)));
end

always @ (*) begin
    ap_block_pp0_stage0_subdone = (((lsc_out_data243_full_n == 1'b0) & (ap_enable_reg_pp0_iter7 == 1'b1)) | ((ltm_in_data242_empty_n == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b1)));
end

assign ap_block_state1_pp0_stage0_iter0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_state2_pp0_stage0_iter1 = (ltm_in_data242_empty_n == 1'b0);
end

assign ap_block_state3_pp0_stage0_iter2 = ~(1'b1 == 1'b1);

assign ap_block_state4_pp0_stage0_iter3 = ~(1'b1 == 1'b1);

assign ap_block_state5_pp0_stage0_iter4 = ~(1'b1 == 1'b1);

assign ap_block_state6_pp0_stage0_iter5 = ~(1'b1 == 1'b1);

assign ap_block_state7_pp0_stage0_iter6 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_state8_pp0_stage0_iter7 = (lsc_out_data243_full_n == 1'b0);
end

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign b_V_fu_176_p4 = {{ltm_in_data242_dout[29:20]}};

assign g_V_fu_166_p4 = {{ltm_in_data242_dout[19:10]}};

assign grp_fu_209_p0 = grp_fu_209_p00;

assign grp_fu_209_p00 = r_V_reg_777;

assign grp_fu_209_p1 = 39'd445737074;

assign grp_fu_218_p0 = zext_ln1316_4_fu_215_p1;

assign grp_fu_218_p1 = 39'd549598081214;

assign grp_fu_224_p0 = zext_ln1316_4_fu_215_p1;

assign grp_fu_224_p1 = 39'd304110528;

assign grp_fu_263_p0 = grp_fu_263_p00;

assign grp_fu_263_p00 = b_V_reg_787_pp0_iter2_reg;

assign grp_fu_263_p1 = 39'd300298744;

assign grp_fu_731_p0 = grp_fu_731_p00;

assign grp_fu_731_p00 = b_V_fu_176_p4;

assign grp_fu_731_p1 = 36'd68699934634;

assign grp_fu_738_p0 = grp_fu_738_p00;

assign grp_fu_738_p00 = r_V_fu_162_p1;

assign grp_fu_738_p1 = 36'd68686029678;

assign grp_fu_745_p0 = grp_fu_745_p00;

assign grp_fu_745_p00 = b_V_fu_176_p4;

assign grp_fu_745_p1 = 33'd8587706577;

assign grp_fu_752_p0 = grp_fu_752_p00;

assign grp_fu_752_p00 = r_V_fu_162_p1;

assign grp_fu_752_p1 = 34'd17174983658;

assign grp_fu_759_p0 = grp_fu_759_p00;

assign grp_fu_759_p00 = g_V_fu_166_p4;

assign grp_fu_759_p1 = 36'd68692472129;

assign icmp_ln1049_1_fu_483_p2 = ((tmp_2_fu_475_p3 == 28'd0) ? 1'b1 : 1'b0);

assign icmp_ln1049_2_fu_557_p2 = ((tmp_4_fu_549_p3 == 28'd0) ? 1'b1 : 1'b0);

assign icmp_ln1049_fu_409_p2 = ((tmp_fu_401_p3 == 28'd0) ? 1'b1 : 1'b0);

assign icmp_ln245_fu_145_p2 = ((ap_sig_allocacmp_j_V_1 == width) ? 1'b1 : 1'b0);

assign icmp_ln97_1_fu_657_p2 = (($signed(tmp_20_reg_898) > $signed(5'd0)) ? 1'b1 : 1'b0);

assign icmp_ln97_2_fu_690_p2 = (($signed(tmp_22_reg_903) > $signed(5'd0)) ? 1'b1 : 1'b0);

assign icmp_ln97_fu_624_p2 = (($signed(tmp_18_reg_893) > $signed(5'd0)) ? 1'b1 : 1'b0);

assign j_V_2_fu_151_p2 = (ap_sig_allocacmp_j_V_1 + 11'd1);

assign lsc_out_data243_din = {{{select_ln260_2_reg_918}, {select_ln260_1_reg_913}}, {select_ln260_reg_908}};

assign p_Result_1_fu_463_p3 = ret_V_16_fu_443_p2[32'd21];

assign p_Result_2_fu_537_p3 = ret_V_19_fu_517_p2[32'd21];

assign p_Result_s_fu_389_p3 = ret_V_13_fu_369_p2[32'd21];

assign r_V_fu_162_p1 = ltm_in_data242_dout[9:0];

assign ret_V_10_fu_563_p2 = ($signed(sext_ln1048_2_fu_533_p1) + $signed(15'd1));

assign ret_V_12_fu_330_p2 = ($signed(sext_ln1393_fu_327_p1) + $signed(zext_ln1393_fu_324_p1));

assign ret_V_13_fu_369_p2 = ($signed(sext_ln1393_1_fu_363_p1) + $signed(sext_ln1393_2_fu_366_p1));

assign ret_V_14_fu_429_p3 = ((p_Result_s_fu_389_p3[0:0] == 1'b1) ? select_ln1048_fu_421_p3 : sext_ln1048_fu_385_p1);

assign ret_V_15_fu_343_p2 = ($signed(zext_ln1393_1_fu_340_p1) + $signed(sext_ln1393_3_fu_336_p1));

assign ret_V_16_fu_443_p2 = ($signed(sext_ln1393_4_fu_437_p1) + $signed(sext_ln1393_5_fu_440_p1));

assign ret_V_17_fu_503_p3 = ((p_Result_1_fu_463_p3[0:0] == 1'b1) ? select_ln1048_1_fu_495_p3 : sext_ln1048_1_fu_459_p1);

assign ret_V_18_fu_357_p2 = ($signed(sext_ln1393_7_fu_353_p1) + $signed(sext_ln1393_6_fu_349_p1));

assign ret_V_19_fu_517_p2 = ($signed(sext_ln1393_8_fu_511_p1) + $signed(zext_ln1393_2_fu_514_p1));

assign ret_V_20_fu_577_p3 = ((p_Result_2_fu_537_p3[0:0] == 1'b1) ? select_ln1048_2_fu_569_p3 : sext_ln1048_2_fu_533_p1);

assign ret_V_6_fu_489_p2 = ($signed(sext_ln1048_1_fu_459_p1) + $signed(15'd1));

assign ret_V_fu_415_p2 = ($signed(sext_ln1048_fu_385_p1) + $signed(15'd1));

assign select_ln1048_1_fu_495_p3 = ((icmp_ln1049_1_fu_483_p2[0:0] == 1'b1) ? sext_ln1048_1_fu_459_p1 : ret_V_6_fu_489_p2);

assign select_ln1048_2_fu_569_p3 = ((icmp_ln1049_2_fu_557_p2[0:0] == 1'b1) ? sext_ln1048_2_fu_533_p1 : ret_V_10_fu_563_p2);

assign select_ln1048_fu_421_p3 = ((icmp_ln1049_fu_409_p2[0:0] == 1'b1) ? sext_ln1048_fu_385_p1 : ret_V_fu_415_p2);

assign select_ln260_1_fu_682_p3 = ((tmp_21_fu_670_p3[0:0] == 1'b1) ? 10'd0 : trunc_ln260_1_fu_678_p1);

assign select_ln260_2_fu_715_p3 = ((tmp_23_fu_703_p3[0:0] == 1'b1) ? 10'd0 : trunc_ln260_2_fu_711_p1);

assign select_ln260_fu_649_p3 = ((tmp_19_fu_637_p3[0:0] == 1'b1) ? 10'd0 : trunc_ln260_fu_645_p1);

assign select_ln97_1_fu_662_p3 = ((icmp_ln97_1_fu_657_p2[0:0] == 1'b1) ? 16'd1023 : sext_ln1029_1_fu_618_p1);

assign select_ln97_2_fu_695_p3 = ((icmp_ln97_2_fu_690_p2[0:0] == 1'b1) ? 16'd1023 : sext_ln1029_2_fu_621_p1);

assign select_ln97_fu_629_p3 = ((icmp_ln97_fu_624_p2[0:0] == 1'b1) ? 16'd1023 : sext_ln1029_fu_615_p1);

assign sext_ln1029_1_fu_618_p1 = ret_V_17_reg_883;

assign sext_ln1029_2_fu_621_p1 = ret_V_20_reg_888;

assign sext_ln1029_fu_615_p1 = ret_V_14_reg_878;

assign sext_ln1048_1_fu_459_p1 = $signed(tmp_5_fu_449_p4);

assign sext_ln1048_2_fu_533_p1 = $signed(tmp_7_fu_523_p4);

assign sext_ln1048_fu_385_p1 = $signed(tmp_1_fu_375_p4);

assign sext_ln1393_1_fu_363_p1 = $signed(ret_V_12_reg_863);

assign sext_ln1393_2_fu_366_p1 = $signed(tmp_8_reg_848);

assign sext_ln1393_3_fu_336_p1 = $signed(tmp_9_fu_278_p4);

assign sext_ln1393_4_fu_437_p1 = $signed(ret_V_15_reg_868);

assign sext_ln1393_5_fu_440_p1 = $signed(tmp_11_reg_853);

assign sext_ln1393_6_fu_349_p1 = $signed(tmp_12_fu_296_p4);

assign sext_ln1393_7_fu_353_p1 = $signed(tmp_13_fu_305_p4);

assign sext_ln1393_8_fu_511_p1 = $signed(ret_V_18_reg_873);

assign sext_ln1393_fu_327_p1 = $signed(tmp_6_reg_833);

assign tmp_12_fu_296_p4 = {{grp_fu_752_p2[33:20]}};

assign tmp_13_fu_305_p4 = {{grp_fu_759_p2[35:20]}};

assign tmp_19_fu_637_p3 = select_ln97_fu_629_p3[32'd15];

assign tmp_1_fu_375_p4 = {{ret_V_13_fu_369_p2[21:8]}};

assign tmp_21_fu_670_p3 = select_ln97_1_fu_662_p3[32'd15];

assign tmp_23_fu_703_p3 = select_ln97_2_fu_695_p3[32'd15];

assign tmp_2_fu_475_p3 = {{trunc_ln1049_1_fu_471_p1}, {20'd0}};

assign tmp_4_fu_549_p3 = {{trunc_ln1049_2_fu_545_p1}, {20'd0}};

assign tmp_5_fu_449_p4 = {{ret_V_16_fu_443_p2[21:8]}};

assign tmp_7_fu_523_p4 = {{ret_V_19_fu_517_p2[21:8]}};

assign tmp_9_fu_278_p4 = {{grp_fu_738_p2[35:20]}};

assign tmp_fu_401_p3 = {{trunc_ln1049_fu_397_p1}, {20'd0}};

assign trunc_ln1049_1_fu_471_p1 = ret_V_16_fu_443_p2[7:0];

assign trunc_ln1049_2_fu_545_p1 = ret_V_19_fu_517_p2[7:0];

assign trunc_ln1049_fu_397_p1 = ret_V_13_fu_369_p2[7:0];

assign trunc_ln260_1_fu_678_p1 = select_ln97_1_fu_662_p3[9:0];

assign trunc_ln260_2_fu_711_p1 = select_ln97_2_fu_695_p3[9:0];

assign trunc_ln260_fu_645_p1 = select_ln97_fu_629_p3[9:0];

assign zext_ln1316_4_fu_215_p1 = g_V_reg_782;

assign zext_ln1393_1_fu_340_p1 = tmp_10_reg_843;

assign zext_ln1393_2_fu_514_p1 = tmp_14_reg_858;

assign zext_ln1393_fu_324_p1 = tmp_3_reg_828;

endmodule //ISPPipeline_accel_xfccmkernel_17_1080_1920_21_1_11_11_1920_2_Pipeline_colLoop
