// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.1 (64-bit)
// Version: 2022.1
// Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module ISPPipeline_accel_rb_kernel_ap_uint_10_5_s (
        ap_clk,
        ap_rst,
        p_read,
        p_read1,
        p_read2,
        p_read3,
        p_read4,
        p_read5,
        p_read6,
        p_read7,
        p_read8,
        ap_return,
        ap_ce
);


input   ap_clk;
input   ap_rst;
input  [9:0] p_read;
input  [9:0] p_read1;
input  [9:0] p_read2;
input  [9:0] p_read3;
input  [9:0] p_read4;
input  [9:0] p_read5;
input  [9:0] p_read6;
input  [9:0] p_read7;
input  [9:0] p_read8;
output  [12:0] ap_return;
input   ap_ce;

reg[12:0] ap_return;

reg   [9:0] p_read413_reg_361;
wire    ap_block_state1_pp0_stage0_iter0;
wire    ap_block_state2_pp0_stage0_iter1;
wire    ap_block_state3_pp0_stage0_iter2;
wire    ap_block_state4_pp0_stage0_iter3;
wire    ap_block_pp0_stage0_11001;
wire   [11:0] ret_V_37_fu_148_p2;
reg   [11:0] ret_V_37_reg_367;
wire   [11:0] ret_V_fu_190_p2;
reg   [11:0] ret_V_reg_373;
reg   [11:0] ret_V_reg_373_pp0_iter1_reg;
wire   [14:0] sub_ln79_fu_262_p2;
reg   [14:0] sub_ln79_reg_378;
reg   [0:0] tmp_reg_383;
reg   [12:0] trunc_ln80_1_reg_388;
reg   [12:0] trunc_ln80_2_reg_393;
wire    ap_block_pp0_stage0;
wire   [10:0] zext_ln232_13_fu_116_p1;
wire   [10:0] zext_ln232_fu_112_p1;
wire   [10:0] ret_V_36_fu_120_p2;
wire   [10:0] zext_ln1541_fu_130_p1;
wire   [10:0] zext_ln1541_17_fu_134_p1;
wire   [10:0] add_ln1541_fu_138_p2;
wire   [11:0] zext_ln1541_18_fu_144_p1;
wire   [11:0] zext_ln232_14_fu_126_p1;
wire   [10:0] zext_ln232_16_fu_158_p1;
wire   [10:0] zext_ln232_15_fu_154_p1;
wire   [10:0] ret_V_38_fu_162_p2;
wire   [10:0] zext_ln1541_19_fu_172_p1;
wire   [10:0] zext_ln1541_20_fu_176_p1;
wire   [10:0] add_ln1541_11_fu_180_p2;
wire   [11:0] zext_ln1541_21_fu_186_p1;
wire   [11:0] zext_ln232_17_fu_168_p1;
wire   [13:0] shl_ln_fu_199_p3;
wire   [14:0] zext_ln75_fu_206_p1;
wire   [14:0] zext_ln74_fu_196_p1;
wire   [14:0] sub_ln75_fu_210_p2;
wire   [13:0] trunc_ln_fu_216_p4;
wire   [12:0] shl_ln4_fu_230_p3;
wire   [10:0] shl_ln78_1_fu_241_p3;
wire   [13:0] zext_ln78_1_fu_237_p1;
wire   [13:0] zext_ln78_2_fu_248_p1;
wire   [13:0] t3_fu_252_p2;
wire  signed [14:0] sext_ln78_fu_258_p1;
wire  signed [14:0] sext_ln232_fu_226_p1;
wire   [12:0] shl_ln3_fu_268_p3;
wire  signed [15:0] sext_ln80_fu_279_p1;
wire   [15:0] zext_ln78_fu_275_p1;
wire   [15:0] add_ln80_fu_282_p2;
wire   [15:0] sub_ln80_fu_296_p2;
wire   [13:0] zext_ln80_fu_322_p1;
wire   [13:0] sub_ln80_1_fu_325_p2;
wire   [13:0] zext_ln80_1_fu_331_p1;
wire   [13:0] res_fu_334_p3;
wire   [0:0] tmp_44_fu_345_p3;
wire   [12:0] trunc_ln79_fu_341_p1;
wire   [12:0] select_ln81_fu_353_p3;
reg    ap_ce_reg;
reg   [9:0] p_read_int_reg;
reg   [9:0] p_read1_int_reg;
reg   [9:0] p_read2_int_reg;
reg   [9:0] p_read3_int_reg;
reg   [9:0] p_read4_int_reg;
reg   [9:0] p_read5_int_reg;
reg   [9:0] p_read6_int_reg;
reg   [9:0] p_read7_int_reg;
reg   [9:0] p_read8_int_reg;
reg   [12:0] ap_return_int_reg;

always @ (posedge ap_clk) begin
    ap_ce_reg <= ap_ce;
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_ce_reg)) begin
        ap_return_int_reg <= select_ln81_fu_353_p3;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_ce)) begin
        p_read1_int_reg <= p_read1;
        p_read2_int_reg <= p_read2;
        p_read3_int_reg <= p_read3;
        p_read4_int_reg <= p_read4;
        p_read5_int_reg <= p_read5;
        p_read6_int_reg <= p_read6;
        p_read7_int_reg <= p_read7;
        p_read8_int_reg <= p_read8;
        p_read_int_reg <= p_read;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce_reg))) begin
        p_read413_reg_361 <= p_read4_int_reg;
        ret_V_37_reg_367 <= ret_V_37_fu_148_p2;
        ret_V_reg_373 <= ret_V_fu_190_p2;
        ret_V_reg_373_pp0_iter1_reg <= ret_V_reg_373;
        sub_ln79_reg_378 <= sub_ln79_fu_262_p2;
        tmp_reg_383 <= add_ln80_fu_282_p2[32'd15];
        trunc_ln80_1_reg_388 <= {{sub_ln80_fu_296_p2[15:3]}};
        trunc_ln80_2_reg_393 <= {{add_ln80_fu_282_p2[15:3]}};
    end
end

always @ (*) begin
    if ((1'b0 == ap_ce_reg)) begin
        ap_return = ap_return_int_reg;
    end else if ((1'b1 == ap_ce_reg)) begin
        ap_return = select_ln81_fu_353_p3;
    end else begin
        ap_return = 'bx;
    end
end

assign add_ln1541_11_fu_180_p2 = (zext_ln1541_19_fu_172_p1 + zext_ln1541_20_fu_176_p1);

assign add_ln1541_fu_138_p2 = (zext_ln1541_fu_130_p1 + zext_ln1541_17_fu_134_p1);

assign add_ln80_fu_282_p2 = ($signed(sext_ln80_fu_279_p1) + $signed(zext_ln78_fu_275_p1));

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_state1_pp0_stage0_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state2_pp0_stage0_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state3_pp0_stage0_iter2 = ~(1'b1 == 1'b1);

assign ap_block_state4_pp0_stage0_iter3 = ~(1'b1 == 1'b1);

assign res_fu_334_p3 = ((tmp_reg_383[0:0] == 1'b1) ? sub_ln80_1_fu_325_p2 : zext_ln80_1_fu_331_p1);

assign ret_V_36_fu_120_p2 = (zext_ln232_13_fu_116_p1 + zext_ln232_fu_112_p1);

assign ret_V_37_fu_148_p2 = (zext_ln1541_18_fu_144_p1 + zext_ln232_14_fu_126_p1);

assign ret_V_38_fu_162_p2 = (zext_ln232_16_fu_158_p1 + zext_ln232_15_fu_154_p1);

assign ret_V_fu_190_p2 = (zext_ln1541_21_fu_186_p1 + zext_ln232_17_fu_168_p1);

assign select_ln81_fu_353_p3 = ((tmp_44_fu_345_p3[0:0] == 1'b1) ? 13'd0 : trunc_ln79_fu_341_p1);

assign sext_ln232_fu_226_p1 = $signed(trunc_ln_fu_216_p4);

assign sext_ln78_fu_258_p1 = $signed(t3_fu_252_p2);

assign sext_ln80_fu_279_p1 = $signed(sub_ln79_reg_378);

assign shl_ln3_fu_268_p3 = {{ret_V_reg_373_pp0_iter1_reg}, {1'd0}};

assign shl_ln4_fu_230_p3 = {{p_read413_reg_361}, {3'd0}};

assign shl_ln78_1_fu_241_p3 = {{p_read413_reg_361}, {1'd0}};

assign shl_ln_fu_199_p3 = {{ret_V_37_reg_367}, {2'd0}};

assign sub_ln75_fu_210_p2 = (zext_ln75_fu_206_p1 - zext_ln74_fu_196_p1);

assign sub_ln79_fu_262_p2 = ($signed(sext_ln78_fu_258_p1) - $signed(sext_ln232_fu_226_p1));

assign sub_ln80_1_fu_325_p2 = (14'd0 - zext_ln80_fu_322_p1);

assign sub_ln80_fu_296_p2 = (16'd0 - add_ln80_fu_282_p2);

assign t3_fu_252_p2 = (zext_ln78_1_fu_237_p1 - zext_ln78_2_fu_248_p1);

assign tmp_44_fu_345_p3 = res_fu_334_p3[32'd13];

assign trunc_ln79_fu_341_p1 = res_fu_334_p3[12:0];

assign trunc_ln_fu_216_p4 = {{sub_ln75_fu_210_p2[14:1]}};

assign zext_ln1541_17_fu_134_p1 = p_read8_int_reg;

assign zext_ln1541_18_fu_144_p1 = add_ln1541_fu_138_p2;

assign zext_ln1541_19_fu_172_p1 = p_read6_int_reg;

assign zext_ln1541_20_fu_176_p1 = p_read7_int_reg;

assign zext_ln1541_21_fu_186_p1 = add_ln1541_11_fu_180_p2;

assign zext_ln1541_fu_130_p1 = p_read5_int_reg;

assign zext_ln232_13_fu_116_p1 = p_read3_int_reg;

assign zext_ln232_14_fu_126_p1 = ret_V_36_fu_120_p2;

assign zext_ln232_15_fu_154_p1 = p_read1_int_reg;

assign zext_ln232_16_fu_158_p1 = p_read2_int_reg;

assign zext_ln232_17_fu_168_p1 = ret_V_38_fu_162_p2;

assign zext_ln232_fu_112_p1 = p_read_int_reg;

assign zext_ln74_fu_196_p1 = ret_V_37_reg_367;

assign zext_ln75_fu_206_p1 = shl_ln_fu_199_p3;

assign zext_ln78_1_fu_237_p1 = shl_ln4_fu_230_p3;

assign zext_ln78_2_fu_248_p1 = shl_ln78_1_fu_241_p3;

assign zext_ln78_fu_275_p1 = shl_ln3_fu_268_p3;

assign zext_ln80_1_fu_331_p1 = trunc_ln80_2_reg_393;

assign zext_ln80_fu_322_p1 = trunc_ln80_1_reg_388;

endmodule //ISPPipeline_accel_rb_kernel_ap_uint_10_5_s
