// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.1 (64-bit)
// Version: 2022.1
// Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module ISPPipeline_accel_function_awb_17_17_1080_1920_1_s (
        ap_clk,
        ap_rst,
        ap_start,
        start_full_n,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready,
        start_out,
        start_write,
        p_read,
        p_read1,
        demosaic_out_data_dout,
        demosaic_out_data_num_data_valid,
        demosaic_out_data_fifo_cap,
        demosaic_out_data_empty_n,
        demosaic_out_data_read,
        p_read2,
        p_read13,
        ltm_in_data_din,
        ltm_in_data_num_data_valid,
        ltm_in_data_fifo_cap,
        ltm_in_data_full_n,
        ltm_in_data_write,
        hist0_0_address0,
        hist0_0_ce0,
        hist0_0_we0,
        hist0_0_d0,
        hist0_1_address0,
        hist0_1_ce0,
        hist0_1_we0,
        hist0_1_d0,
        hist0_2_address0,
        hist0_2_ce0,
        hist0_2_we0,
        hist0_2_d0,
        hist1_0_address0,
        hist1_0_ce0,
        hist1_0_q0,
        hist1_1_address0,
        hist1_1_ce0,
        hist1_1_q0,
        hist1_2_address0,
        hist1_2_ce0,
        hist1_2_q0,
        height,
        width,
        mode_reg,
        p_read24,
        ltm_in_rows_c_din,
        ltm_in_rows_c_num_data_valid,
        ltm_in_rows_c_fifo_cap,
        ltm_in_rows_c_full_n,
        ltm_in_rows_c_write,
        ltm_in_cols_c_din,
        ltm_in_cols_c_num_data_valid,
        ltm_in_cols_c_fifo_cap,
        ltm_in_cols_c_full_n,
        ltm_in_cols_c_write
);

parameter    ap_ST_fsm_state1 = 4'd1;
parameter    ap_ST_fsm_state2 = 4'd2;
parameter    ap_ST_fsm_state3 = 4'd4;
parameter    ap_ST_fsm_state4 = 4'd8;

input   ap_clk;
input   ap_rst;
input   ap_start;
input   start_full_n;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;
output   start_out;
output   start_write;
input  [10:0] p_read;
input  [10:0] p_read1;
input  [29:0] demosaic_out_data_dout;
input  [1:0] demosaic_out_data_num_data_valid;
input  [1:0] demosaic_out_data_fifo_cap;
input   demosaic_out_data_empty_n;
output   demosaic_out_data_read;
input  [10:0] p_read2;
input  [10:0] p_read13;
output  [29:0] ltm_in_data_din;
input  [1:0] ltm_in_data_num_data_valid;
input  [1:0] ltm_in_data_fifo_cap;
input   ltm_in_data_full_n;
output   ltm_in_data_write;
output  [9:0] hist0_0_address0;
output   hist0_0_ce0;
output   hist0_0_we0;
output  [31:0] hist0_0_d0;
output  [9:0] hist0_1_address0;
output   hist0_1_ce0;
output   hist0_1_we0;
output  [31:0] hist0_1_d0;
output  [9:0] hist0_2_address0;
output   hist0_2_ce0;
output   hist0_2_we0;
output  [31:0] hist0_2_d0;
output  [9:0] hist1_0_address0;
output   hist1_0_ce0;
input  [31:0] hist1_0_q0;
output  [9:0] hist1_1_address0;
output   hist1_1_ce0;
input  [31:0] hist1_1_q0;
output  [9:0] hist1_2_address0;
output   hist1_2_ce0;
input  [31:0] hist1_2_q0;
input  [10:0] height;
input  [10:0] width;
input  [0:0] mode_reg;
input  [31:0] p_read24;
output  [10:0] ltm_in_rows_c_din;
input  [1:0] ltm_in_rows_c_num_data_valid;
input  [1:0] ltm_in_rows_c_fifo_cap;
input   ltm_in_rows_c_full_n;
output   ltm_in_rows_c_write;
output  [10:0] ltm_in_cols_c_din;
input  [1:0] ltm_in_cols_c_num_data_valid;
input  [1:0] ltm_in_cols_c_fifo_cap;
input   ltm_in_cols_c_full_n;
output   ltm_in_cols_c_write;

reg ap_done;
reg ap_idle;
reg start_write;
reg demosaic_out_data_read;
reg[29:0] ltm_in_data_din;
reg ltm_in_data_write;
reg ltm_in_rows_c_write;
reg ltm_in_cols_c_write;

reg    real_start;
reg    start_once_reg;
reg    ap_done_reg;
(* fsm_encoding = "none" *) reg   [3:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    internal_ap_ready;
reg    ltm_in_rows_c_blk_n;
reg    ltm_in_cols_c_blk_n;
wire   [0:0] mode_reg_read_read_fu_98_p2;
wire    grp_fifo_copy_17_17_1080_1920_1_s_fu_156_ap_start;
wire    grp_fifo_copy_17_17_1080_1920_1_s_fu_156_ap_done;
wire    grp_fifo_copy_17_17_1080_1920_1_s_fu_156_ap_idle;
wire    grp_fifo_copy_17_17_1080_1920_1_s_fu_156_ap_ready;
wire    grp_fifo_copy_17_17_1080_1920_1_s_fu_156_demosaic_out_data241_read;
wire   [29:0] grp_fifo_copy_17_17_1080_1920_1_s_fu_156_ltm_in_data242_din;
wire    grp_fifo_copy_17_17_1080_1920_1_s_fu_156_ltm_in_data242_write;
wire    grp_fifo_awb_17_17_1080_1920_1_s_fu_168_demosaic_out_data241_read;
wire   [29:0] grp_fifo_awb_17_17_1080_1920_1_s_fu_168_ltm_in_data242_din;
wire    grp_fifo_awb_17_17_1080_1920_1_s_fu_168_ltm_in_data242_write;
wire   [9:0] grp_fifo_awb_17_17_1080_1920_1_s_fu_168_hist0_0_address0;
wire    grp_fifo_awb_17_17_1080_1920_1_s_fu_168_hist0_0_ce0;
wire   [31:0] grp_fifo_awb_17_17_1080_1920_1_s_fu_168_hist0_0_d0;
wire    grp_fifo_awb_17_17_1080_1920_1_s_fu_168_hist0_0_we0;
wire   [9:0] grp_fifo_awb_17_17_1080_1920_1_s_fu_168_hist0_0_address1;
wire    grp_fifo_awb_17_17_1080_1920_1_s_fu_168_hist0_0_ce1;
wire   [31:0] grp_fifo_awb_17_17_1080_1920_1_s_fu_168_hist0_0_d1;
wire    grp_fifo_awb_17_17_1080_1920_1_s_fu_168_hist0_0_we1;
wire   [9:0] grp_fifo_awb_17_17_1080_1920_1_s_fu_168_hist0_1_address0;
wire    grp_fifo_awb_17_17_1080_1920_1_s_fu_168_hist0_1_ce0;
wire   [31:0] grp_fifo_awb_17_17_1080_1920_1_s_fu_168_hist0_1_d0;
wire    grp_fifo_awb_17_17_1080_1920_1_s_fu_168_hist0_1_we0;
wire   [9:0] grp_fifo_awb_17_17_1080_1920_1_s_fu_168_hist0_1_address1;
wire    grp_fifo_awb_17_17_1080_1920_1_s_fu_168_hist0_1_ce1;
wire   [31:0] grp_fifo_awb_17_17_1080_1920_1_s_fu_168_hist0_1_d1;
wire    grp_fifo_awb_17_17_1080_1920_1_s_fu_168_hist0_1_we1;
wire   [9:0] grp_fifo_awb_17_17_1080_1920_1_s_fu_168_hist0_2_address0;
wire    grp_fifo_awb_17_17_1080_1920_1_s_fu_168_hist0_2_ce0;
wire   [31:0] grp_fifo_awb_17_17_1080_1920_1_s_fu_168_hist0_2_d0;
wire    grp_fifo_awb_17_17_1080_1920_1_s_fu_168_hist0_2_we0;
wire   [9:0] grp_fifo_awb_17_17_1080_1920_1_s_fu_168_hist0_2_address1;
wire    grp_fifo_awb_17_17_1080_1920_1_s_fu_168_hist0_2_ce1;
wire   [31:0] grp_fifo_awb_17_17_1080_1920_1_s_fu_168_hist0_2_d1;
wire    grp_fifo_awb_17_17_1080_1920_1_s_fu_168_hist0_2_we1;
wire   [9:0] grp_fifo_awb_17_17_1080_1920_1_s_fu_168_hist1_0_address0;
wire    grp_fifo_awb_17_17_1080_1920_1_s_fu_168_hist1_0_ce0;
wire   [31:0] grp_fifo_awb_17_17_1080_1920_1_s_fu_168_hist1_0_d0;
wire    grp_fifo_awb_17_17_1080_1920_1_s_fu_168_hist1_0_we0;
wire   [9:0] grp_fifo_awb_17_17_1080_1920_1_s_fu_168_hist1_0_address1;
wire    grp_fifo_awb_17_17_1080_1920_1_s_fu_168_hist1_0_ce1;
wire   [31:0] grp_fifo_awb_17_17_1080_1920_1_s_fu_168_hist1_0_d1;
wire    grp_fifo_awb_17_17_1080_1920_1_s_fu_168_hist1_0_we1;
wire   [9:0] grp_fifo_awb_17_17_1080_1920_1_s_fu_168_hist1_1_address0;
wire    grp_fifo_awb_17_17_1080_1920_1_s_fu_168_hist1_1_ce0;
wire   [31:0] grp_fifo_awb_17_17_1080_1920_1_s_fu_168_hist1_1_d0;
wire    grp_fifo_awb_17_17_1080_1920_1_s_fu_168_hist1_1_we0;
wire   [9:0] grp_fifo_awb_17_17_1080_1920_1_s_fu_168_hist1_1_address1;
wire    grp_fifo_awb_17_17_1080_1920_1_s_fu_168_hist1_1_ce1;
wire   [31:0] grp_fifo_awb_17_17_1080_1920_1_s_fu_168_hist1_1_d1;
wire    grp_fifo_awb_17_17_1080_1920_1_s_fu_168_hist1_1_we1;
wire   [9:0] grp_fifo_awb_17_17_1080_1920_1_s_fu_168_hist1_2_address0;
wire    grp_fifo_awb_17_17_1080_1920_1_s_fu_168_hist1_2_ce0;
wire   [31:0] grp_fifo_awb_17_17_1080_1920_1_s_fu_168_hist1_2_d0;
wire    grp_fifo_awb_17_17_1080_1920_1_s_fu_168_hist1_2_we0;
wire   [9:0] grp_fifo_awb_17_17_1080_1920_1_s_fu_168_hist1_2_address1;
wire    grp_fifo_awb_17_17_1080_1920_1_s_fu_168_hist1_2_ce1;
wire   [31:0] grp_fifo_awb_17_17_1080_1920_1_s_fu_168_hist1_2_d1;
wire    grp_fifo_awb_17_17_1080_1920_1_s_fu_168_hist1_2_we1;
wire    grp_fifo_awb_17_17_1080_1920_1_s_fu_168_ap_start;
wire    grp_fifo_awb_17_17_1080_1920_1_s_fu_168_ap_done;
wire    grp_fifo_awb_17_17_1080_1920_1_s_fu_168_ap_ready;
wire    grp_fifo_awb_17_17_1080_1920_1_s_fu_168_ap_idle;
reg    grp_fifo_awb_17_17_1080_1920_1_s_fu_168_ap_continue;
reg    grp_fifo_copy_17_17_1080_1920_1_s_fu_156_ap_start_reg;
reg    ap_block_state1_ignore_call0;
wire    ap_CS_fsm_state2;
reg    grp_fifo_awb_17_17_1080_1920_1_s_fu_168_ap_start_reg;
wire    ap_CS_fsm_state3;
wire    ap_CS_fsm_state4;
wire    ap_sync_grp_fifo_awb_17_17_1080_1920_1_s_fu_168_ap_ready;
wire    ap_sync_grp_fifo_awb_17_17_1080_1920_1_s_fu_168_ap_done;
reg    ap_block_state4_on_subcall_done;
reg    ap_sync_reg_grp_fifo_awb_17_17_1080_1920_1_s_fu_168_ap_ready;
reg    ap_sync_reg_grp_fifo_awb_17_17_1080_1920_1_s_fu_168_ap_done;
reg    ap_block_state1;
reg   [3:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
reg    ap_ST_fsm_state2_blk;
wire    ap_ST_fsm_state3_blk;
reg    ap_ST_fsm_state4_blk;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 start_once_reg = 1'b0;
#0 ap_done_reg = 1'b0;
#0 ap_CS_fsm = 4'd1;
#0 grp_fifo_copy_17_17_1080_1920_1_s_fu_156_ap_start_reg = 1'b0;
#0 grp_fifo_awb_17_17_1080_1920_1_s_fu_168_ap_start_reg = 1'b0;
#0 ap_sync_reg_grp_fifo_awb_17_17_1080_1920_1_s_fu_168_ap_ready = 1'b0;
#0 ap_sync_reg_grp_fifo_awb_17_17_1080_1920_1_s_fu_168_ap_done = 1'b0;
end

ISPPipeline_accel_fifo_copy_17_17_1080_1920_1_s grp_fifo_copy_17_17_1080_1920_1_s_fu_156(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_fifo_copy_17_17_1080_1920_1_s_fu_156_ap_start),
    .ap_done(grp_fifo_copy_17_17_1080_1920_1_s_fu_156_ap_done),
    .ap_idle(grp_fifo_copy_17_17_1080_1920_1_s_fu_156_ap_idle),
    .ap_ready(grp_fifo_copy_17_17_1080_1920_1_s_fu_156_ap_ready),
    .demosaic_out_data241_dout(demosaic_out_data_dout),
    .demosaic_out_data241_num_data_valid(2'd0),
    .demosaic_out_data241_fifo_cap(2'd0),
    .demosaic_out_data241_empty_n(demosaic_out_data_empty_n),
    .demosaic_out_data241_read(grp_fifo_copy_17_17_1080_1920_1_s_fu_156_demosaic_out_data241_read),
    .ltm_in_data242_din(grp_fifo_copy_17_17_1080_1920_1_s_fu_156_ltm_in_data242_din),
    .ltm_in_data242_num_data_valid(2'd0),
    .ltm_in_data242_fifo_cap(2'd0),
    .ltm_in_data242_full_n(ltm_in_data_full_n),
    .ltm_in_data242_write(grp_fifo_copy_17_17_1080_1920_1_s_fu_156_ltm_in_data242_write),
    .height(height),
    .width(width)
);

ISPPipeline_accel_fifo_awb_17_17_1080_1920_1_s grp_fifo_awb_17_17_1080_1920_1_s_fu_168(
    .p_read(p_read),
    .p_read1(p_read1),
    .demosaic_out_data241_dout(demosaic_out_data_dout),
    .demosaic_out_data241_empty_n(demosaic_out_data_empty_n),
    .demosaic_out_data241_read(grp_fifo_awb_17_17_1080_1920_1_s_fu_168_demosaic_out_data241_read),
    .p_read2(p_read2),
    .p_read3(p_read13),
    .ltm_in_data242_din(grp_fifo_awb_17_17_1080_1920_1_s_fu_168_ltm_in_data242_din),
    .ltm_in_data242_full_n(ltm_in_data_full_n),
    .ltm_in_data242_write(grp_fifo_awb_17_17_1080_1920_1_s_fu_168_ltm_in_data242_write),
    .hist0_0_address0(grp_fifo_awb_17_17_1080_1920_1_s_fu_168_hist0_0_address0),
    .hist0_0_ce0(grp_fifo_awb_17_17_1080_1920_1_s_fu_168_hist0_0_ce0),
    .hist0_0_d0(grp_fifo_awb_17_17_1080_1920_1_s_fu_168_hist0_0_d0),
    .hist0_0_q0(32'd0),
    .hist0_0_we0(grp_fifo_awb_17_17_1080_1920_1_s_fu_168_hist0_0_we0),
    .hist0_0_address1(grp_fifo_awb_17_17_1080_1920_1_s_fu_168_hist0_0_address1),
    .hist0_0_ce1(grp_fifo_awb_17_17_1080_1920_1_s_fu_168_hist0_0_ce1),
    .hist0_0_d1(grp_fifo_awb_17_17_1080_1920_1_s_fu_168_hist0_0_d1),
    .hist0_0_q1(32'd0),
    .hist0_0_we1(grp_fifo_awb_17_17_1080_1920_1_s_fu_168_hist0_0_we1),
    .hist0_1_address0(grp_fifo_awb_17_17_1080_1920_1_s_fu_168_hist0_1_address0),
    .hist0_1_ce0(grp_fifo_awb_17_17_1080_1920_1_s_fu_168_hist0_1_ce0),
    .hist0_1_d0(grp_fifo_awb_17_17_1080_1920_1_s_fu_168_hist0_1_d0),
    .hist0_1_q0(32'd0),
    .hist0_1_we0(grp_fifo_awb_17_17_1080_1920_1_s_fu_168_hist0_1_we0),
    .hist0_1_address1(grp_fifo_awb_17_17_1080_1920_1_s_fu_168_hist0_1_address1),
    .hist0_1_ce1(grp_fifo_awb_17_17_1080_1920_1_s_fu_168_hist0_1_ce1),
    .hist0_1_d1(grp_fifo_awb_17_17_1080_1920_1_s_fu_168_hist0_1_d1),
    .hist0_1_q1(32'd0),
    .hist0_1_we1(grp_fifo_awb_17_17_1080_1920_1_s_fu_168_hist0_1_we1),
    .hist0_2_address0(grp_fifo_awb_17_17_1080_1920_1_s_fu_168_hist0_2_address0),
    .hist0_2_ce0(grp_fifo_awb_17_17_1080_1920_1_s_fu_168_hist0_2_ce0),
    .hist0_2_d0(grp_fifo_awb_17_17_1080_1920_1_s_fu_168_hist0_2_d0),
    .hist0_2_q0(32'd0),
    .hist0_2_we0(grp_fifo_awb_17_17_1080_1920_1_s_fu_168_hist0_2_we0),
    .hist0_2_address1(grp_fifo_awb_17_17_1080_1920_1_s_fu_168_hist0_2_address1),
    .hist0_2_ce1(grp_fifo_awb_17_17_1080_1920_1_s_fu_168_hist0_2_ce1),
    .hist0_2_d1(grp_fifo_awb_17_17_1080_1920_1_s_fu_168_hist0_2_d1),
    .hist0_2_q1(32'd0),
    .hist0_2_we1(grp_fifo_awb_17_17_1080_1920_1_s_fu_168_hist0_2_we1),
    .hist1_0_address0(grp_fifo_awb_17_17_1080_1920_1_s_fu_168_hist1_0_address0),
    .hist1_0_ce0(grp_fifo_awb_17_17_1080_1920_1_s_fu_168_hist1_0_ce0),
    .hist1_0_d0(grp_fifo_awb_17_17_1080_1920_1_s_fu_168_hist1_0_d0),
    .hist1_0_q0(hist1_0_q0),
    .hist1_0_we0(grp_fifo_awb_17_17_1080_1920_1_s_fu_168_hist1_0_we0),
    .hist1_0_address1(grp_fifo_awb_17_17_1080_1920_1_s_fu_168_hist1_0_address1),
    .hist1_0_ce1(grp_fifo_awb_17_17_1080_1920_1_s_fu_168_hist1_0_ce1),
    .hist1_0_d1(grp_fifo_awb_17_17_1080_1920_1_s_fu_168_hist1_0_d1),
    .hist1_0_q1(32'd0),
    .hist1_0_we1(grp_fifo_awb_17_17_1080_1920_1_s_fu_168_hist1_0_we1),
    .hist1_1_address0(grp_fifo_awb_17_17_1080_1920_1_s_fu_168_hist1_1_address0),
    .hist1_1_ce0(grp_fifo_awb_17_17_1080_1920_1_s_fu_168_hist1_1_ce0),
    .hist1_1_d0(grp_fifo_awb_17_17_1080_1920_1_s_fu_168_hist1_1_d0),
    .hist1_1_q0(hist1_1_q0),
    .hist1_1_we0(grp_fifo_awb_17_17_1080_1920_1_s_fu_168_hist1_1_we0),
    .hist1_1_address1(grp_fifo_awb_17_17_1080_1920_1_s_fu_168_hist1_1_address1),
    .hist1_1_ce1(grp_fifo_awb_17_17_1080_1920_1_s_fu_168_hist1_1_ce1),
    .hist1_1_d1(grp_fifo_awb_17_17_1080_1920_1_s_fu_168_hist1_1_d1),
    .hist1_1_q1(32'd0),
    .hist1_1_we1(grp_fifo_awb_17_17_1080_1920_1_s_fu_168_hist1_1_we1),
    .hist1_2_address0(grp_fifo_awb_17_17_1080_1920_1_s_fu_168_hist1_2_address0),
    .hist1_2_ce0(grp_fifo_awb_17_17_1080_1920_1_s_fu_168_hist1_2_ce0),
    .hist1_2_d0(grp_fifo_awb_17_17_1080_1920_1_s_fu_168_hist1_2_d0),
    .hist1_2_q0(hist1_2_q0),
    .hist1_2_we0(grp_fifo_awb_17_17_1080_1920_1_s_fu_168_hist1_2_we0),
    .hist1_2_address1(grp_fifo_awb_17_17_1080_1920_1_s_fu_168_hist1_2_address1),
    .hist1_2_ce1(grp_fifo_awb_17_17_1080_1920_1_s_fu_168_hist1_2_ce1),
    .hist1_2_d1(grp_fifo_awb_17_17_1080_1920_1_s_fu_168_hist1_2_d1),
    .hist1_2_q1(32'd0),
    .hist1_2_we1(grp_fifo_awb_17_17_1080_1920_1_s_fu_168_hist1_2_we1),
    .thresh(p_read24),
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .p_read_ap_vld(1'b1),
    .p_read1_ap_vld(1'b1),
    .ap_start(grp_fifo_awb_17_17_1080_1920_1_s_fu_168_ap_start),
    .ap_done(grp_fifo_awb_17_17_1080_1920_1_s_fu_168_ap_done),
    .p_read2_ap_vld(1'b1),
    .p_read3_ap_vld(1'b1),
    .thresh_ap_vld(1'b1),
    .ap_ready(grp_fifo_awb_17_17_1080_1920_1_s_fu_168_ap_ready),
    .ap_idle(grp_fifo_awb_17_17_1080_1920_1_s_fu_168_ap_idle),
    .ap_continue(grp_fifo_awb_17_17_1080_1920_1_s_fu_168_ap_continue)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((1'b0 == ap_block_state4_on_subcall_done) & (1'b1 == ap_CS_fsm_state4))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_sync_reg_grp_fifo_awb_17_17_1080_1920_1_s_fu_168_ap_done <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_state4_on_subcall_done) & (1'b1 == ap_CS_fsm_state4) & (mode_reg == 1'd1))) begin
            ap_sync_reg_grp_fifo_awb_17_17_1080_1920_1_s_fu_168_ap_done <= 1'b0;
        end else if ((grp_fifo_awb_17_17_1080_1920_1_s_fu_168_ap_done == 1'b1)) begin
            ap_sync_reg_grp_fifo_awb_17_17_1080_1920_1_s_fu_168_ap_done <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_sync_reg_grp_fifo_awb_17_17_1080_1920_1_s_fu_168_ap_ready <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_state4_on_subcall_done) & (1'b1 == ap_CS_fsm_state4) & (mode_reg == 1'd1))) begin
            ap_sync_reg_grp_fifo_awb_17_17_1080_1920_1_s_fu_168_ap_ready <= 1'b0;
        end else if ((grp_fifo_awb_17_17_1080_1920_1_s_fu_168_ap_ready == 1'b1)) begin
            ap_sync_reg_grp_fifo_awb_17_17_1080_1920_1_s_fu_168_ap_ready <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_fifo_awb_17_17_1080_1920_1_s_fu_168_ap_start_reg <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_state3) | ((ap_sync_grp_fifo_awb_17_17_1080_1920_1_s_fu_168_ap_ready == 1'b0) & (1'b1 == ap_CS_fsm_state4) & (mode_reg == 1'd1)))) begin
            grp_fifo_awb_17_17_1080_1920_1_s_fu_168_ap_start_reg <= 1'b1;
        end else if ((grp_fifo_awb_17_17_1080_1920_1_s_fu_168_ap_ready == 1'b1)) begin
            grp_fifo_awb_17_17_1080_1920_1_s_fu_168_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_fifo_copy_17_17_1080_1920_1_s_fu_156_ap_start_reg <= 1'b0;
    end else begin
        if ((~((ap_done_reg == 1'b1) | (real_start == 1'b0) | (ltm_in_cols_c_full_n == 1'b0) | (ltm_in_rows_c_full_n == 1'b0)) & (1'b1 == ap_CS_fsm_state1) & (mode_reg_read_read_fu_98_p2 == 1'd0))) begin
            grp_fifo_copy_17_17_1080_1920_1_s_fu_156_ap_start_reg <= 1'b1;
        end else if ((grp_fifo_copy_17_17_1080_1920_1_s_fu_156_ap_ready == 1'b1)) begin
            grp_fifo_copy_17_17_1080_1920_1_s_fu_156_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        start_once_reg <= 1'b0;
    end else begin
        if (((internal_ap_ready == 1'b0) & (real_start == 1'b1))) begin
            start_once_reg <= 1'b1;
        end else if ((internal_ap_ready == 1'b1)) begin
            start_once_reg <= 1'b0;
        end
    end
end

always @ (*) begin
    if (((ap_done_reg == 1'b1) | (real_start == 1'b0) | (ltm_in_cols_c_full_n == 1'b0) | (ltm_in_rows_c_full_n == 1'b0))) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

always @ (*) begin
    if ((grp_fifo_copy_17_17_1080_1920_1_s_fu_156_ap_done == 1'b0)) begin
        ap_ST_fsm_state2_blk = 1'b1;
    end else begin
        ap_ST_fsm_state2_blk = 1'b0;
    end
end

assign ap_ST_fsm_state3_blk = 1'b0;

always @ (*) begin
    if ((1'b1 == ap_block_state4_on_subcall_done)) begin
        ap_ST_fsm_state4_blk = 1'b1;
    end else begin
        ap_ST_fsm_state4_blk = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state4_on_subcall_done) & (1'b1 == ap_CS_fsm_state4))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = ap_done_reg;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (real_start == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state4) & (mode_reg == 1'd1))) begin
        demosaic_out_data_read = grp_fifo_awb_17_17_1080_1920_1_s_fu_168_demosaic_out_data241_read;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        demosaic_out_data_read = grp_fifo_copy_17_17_1080_1920_1_s_fu_156_demosaic_out_data241_read;
    end else begin
        demosaic_out_data_read = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state4_on_subcall_done) & (1'b1 == ap_CS_fsm_state4) & (mode_reg == 1'd1))) begin
        grp_fifo_awb_17_17_1080_1920_1_s_fu_168_ap_continue = 1'b1;
    end else begin
        grp_fifo_awb_17_17_1080_1920_1_s_fu_168_ap_continue = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state4_on_subcall_done) & (1'b1 == ap_CS_fsm_state4))) begin
        internal_ap_ready = 1'b1;
    end else begin
        internal_ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_done_reg == 1'b1) | (real_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
        ltm_in_cols_c_blk_n = ltm_in_cols_c_full_n;
    end else begin
        ltm_in_cols_c_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((ap_done_reg == 1'b1) | (real_start == 1'b0) | (ltm_in_cols_c_full_n == 1'b0) | (ltm_in_rows_c_full_n == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
        ltm_in_cols_c_write = 1'b1;
    end else begin
        ltm_in_cols_c_write = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state4) & (mode_reg == 1'd1))) begin
        ltm_in_data_din = grp_fifo_awb_17_17_1080_1920_1_s_fu_168_ltm_in_data242_din;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        ltm_in_data_din = grp_fifo_copy_17_17_1080_1920_1_s_fu_156_ltm_in_data242_din;
    end else begin
        ltm_in_data_din = grp_fifo_awb_17_17_1080_1920_1_s_fu_168_ltm_in_data242_din;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state4) & (mode_reg == 1'd1))) begin
        ltm_in_data_write = grp_fifo_awb_17_17_1080_1920_1_s_fu_168_ltm_in_data242_write;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        ltm_in_data_write = grp_fifo_copy_17_17_1080_1920_1_s_fu_156_ltm_in_data242_write;
    end else begin
        ltm_in_data_write = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_done_reg == 1'b1) | (real_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
        ltm_in_rows_c_blk_n = ltm_in_rows_c_full_n;
    end else begin
        ltm_in_rows_c_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((ap_done_reg == 1'b1) | (real_start == 1'b0) | (ltm_in_cols_c_full_n == 1'b0) | (ltm_in_rows_c_full_n == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
        ltm_in_rows_c_write = 1'b1;
    end else begin
        ltm_in_rows_c_write = 1'b0;
    end
end

always @ (*) begin
    if (((start_once_reg == 1'b0) & (start_full_n == 1'b0))) begin
        real_start = 1'b0;
    end else begin
        real_start = ap_start;
    end
end

always @ (*) begin
    if (((start_once_reg == 1'b0) & (real_start == 1'b1))) begin
        start_write = 1'b1;
    end else begin
        start_write = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if ((~((ap_done_reg == 1'b1) | (real_start == 1'b0) | (ltm_in_cols_c_full_n == 1'b0) | (ltm_in_rows_c_full_n == 1'b0)) & (1'b1 == ap_CS_fsm_state1) & (mode_reg == 1'd1))) begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end else if ((~((ap_done_reg == 1'b1) | (real_start == 1'b0) | (ltm_in_cols_c_full_n == 1'b0) | (ltm_in_rows_c_full_n == 1'b0)) & (1'b1 == ap_CS_fsm_state1) & (mode_reg_read_read_fu_98_p2 == 1'd0))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((1'b1 == ap_CS_fsm_state2) & (grp_fifo_copy_17_17_1080_1920_1_s_fu_156_ap_done == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end
        end
        ap_ST_fsm_state3 : begin
            ap_NS_fsm = ap_ST_fsm_state4;
        end
        ap_ST_fsm_state4 : begin
            if (((1'b0 == ap_block_state4_on_subcall_done) & (1'b1 == ap_CS_fsm_state4))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

always @ (*) begin
    ap_block_state1 = ((ap_done_reg == 1'b1) | (real_start == 1'b0) | (ltm_in_cols_c_full_n == 1'b0) | (ltm_in_rows_c_full_n == 1'b0));
end

always @ (*) begin
    ap_block_state1_ignore_call0 = ((ap_done_reg == 1'b1) | (real_start == 1'b0) | (ltm_in_cols_c_full_n == 1'b0) | (ltm_in_rows_c_full_n == 1'b0));
end

always @ (*) begin
    ap_block_state4_on_subcall_done = (((ap_sync_grp_fifo_awb_17_17_1080_1920_1_s_fu_168_ap_ready & ap_sync_grp_fifo_awb_17_17_1080_1920_1_s_fu_168_ap_done) == 1'b0) & (mode_reg == 1'd1));
end

assign ap_ready = internal_ap_ready;

assign ap_sync_grp_fifo_awb_17_17_1080_1920_1_s_fu_168_ap_done = (grp_fifo_awb_17_17_1080_1920_1_s_fu_168_ap_done | ap_sync_reg_grp_fifo_awb_17_17_1080_1920_1_s_fu_168_ap_done);

assign ap_sync_grp_fifo_awb_17_17_1080_1920_1_s_fu_168_ap_ready = (grp_fifo_awb_17_17_1080_1920_1_s_fu_168_ap_ready | ap_sync_reg_grp_fifo_awb_17_17_1080_1920_1_s_fu_168_ap_ready);

assign grp_fifo_awb_17_17_1080_1920_1_s_fu_168_ap_start = grp_fifo_awb_17_17_1080_1920_1_s_fu_168_ap_start_reg;

assign grp_fifo_copy_17_17_1080_1920_1_s_fu_156_ap_start = grp_fifo_copy_17_17_1080_1920_1_s_fu_156_ap_start_reg;

assign hist0_0_address0 = grp_fifo_awb_17_17_1080_1920_1_s_fu_168_hist0_0_address0;

assign hist0_0_ce0 = grp_fifo_awb_17_17_1080_1920_1_s_fu_168_hist0_0_ce0;

assign hist0_0_d0 = grp_fifo_awb_17_17_1080_1920_1_s_fu_168_hist0_0_d0;

assign hist0_0_we0 = grp_fifo_awb_17_17_1080_1920_1_s_fu_168_hist0_0_we0;

assign hist0_1_address0 = grp_fifo_awb_17_17_1080_1920_1_s_fu_168_hist0_1_address0;

assign hist0_1_ce0 = grp_fifo_awb_17_17_1080_1920_1_s_fu_168_hist0_1_ce0;

assign hist0_1_d0 = grp_fifo_awb_17_17_1080_1920_1_s_fu_168_hist0_1_d0;

assign hist0_1_we0 = grp_fifo_awb_17_17_1080_1920_1_s_fu_168_hist0_1_we0;

assign hist0_2_address0 = grp_fifo_awb_17_17_1080_1920_1_s_fu_168_hist0_2_address0;

assign hist0_2_ce0 = grp_fifo_awb_17_17_1080_1920_1_s_fu_168_hist0_2_ce0;

assign hist0_2_d0 = grp_fifo_awb_17_17_1080_1920_1_s_fu_168_hist0_2_d0;

assign hist0_2_we0 = grp_fifo_awb_17_17_1080_1920_1_s_fu_168_hist0_2_we0;

assign hist1_0_address0 = grp_fifo_awb_17_17_1080_1920_1_s_fu_168_hist1_0_address0;

assign hist1_0_ce0 = grp_fifo_awb_17_17_1080_1920_1_s_fu_168_hist1_0_ce0;

assign hist1_1_address0 = grp_fifo_awb_17_17_1080_1920_1_s_fu_168_hist1_1_address0;

assign hist1_1_ce0 = grp_fifo_awb_17_17_1080_1920_1_s_fu_168_hist1_1_ce0;

assign hist1_2_address0 = grp_fifo_awb_17_17_1080_1920_1_s_fu_168_hist1_2_address0;

assign hist1_2_ce0 = grp_fifo_awb_17_17_1080_1920_1_s_fu_168_hist1_2_ce0;

assign ltm_in_cols_c_din = p_read13;

assign ltm_in_rows_c_din = p_read2;

assign mode_reg_read_read_fu_98_p2 = mode_reg;

assign start_out = real_start;

endmodule //ISPPipeline_accel_function_awb_17_17_1080_1920_1_s
