// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.1 (64-bit)
// Version: 2022.1
// Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module ISPPipeline_accel_demosaicing_3_13_17_1080_1920_1_false_Pipeline_Col_Loop (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        gain_out_data240_dout,
        gain_out_data240_num_data_valid,
        gain_out_data240_fifo_cap,
        gain_out_data240_empty_n,
        gain_out_data240_read,
        demosaic_out_data241_din,
        demosaic_out_data241_num_data_valid,
        demosaic_out_data241_fifo_cap,
        demosaic_out_data241_full_n,
        demosaic_out_data241_write,
        p_Val2_18,
        imgblock_V_17_1_reload,
        p_Val2_21,
        p_Val2_17,
        imgblock_V_12_1_reload,
        imgblock_V_11_1_reload,
        p_Val2_16,
        imgblock_V_7_1_reload,
        p_Val2_22,
        p_Val2_20,
        p_Val2_19,
        p_Val2_s,
        p_read1,
        trunc_ln,
        linebuffer_V_address0,
        linebuffer_V_ce0,
        linebuffer_V_we0,
        linebuffer_V_d0,
        linebuffer_V_address1,
        linebuffer_V_ce1,
        linebuffer_V_q1,
        linebuffer_V_1_address0,
        linebuffer_V_1_ce0,
        linebuffer_V_1_we0,
        linebuffer_V_1_d0,
        linebuffer_V_1_address1,
        linebuffer_V_1_ce1,
        linebuffer_V_1_q1,
        linebuffer_V_2_address0,
        linebuffer_V_2_ce0,
        linebuffer_V_2_we0,
        linebuffer_V_2_d0,
        linebuffer_V_2_address1,
        linebuffer_V_2_ce1,
        linebuffer_V_2_q1,
        linebuffer_V_3_address0,
        linebuffer_V_3_ce0,
        linebuffer_V_3_we0,
        linebuffer_V_3_d0,
        linebuffer_V_3_address1,
        linebuffer_V_3_ce1,
        linebuffer_V_3_q1,
        line0_V_1,
        line1_V,
        line2_V,
        line3_V,
        lineStore_1_cast,
        sub219,
        cmp162,
        imgblock_V_12_out,
        imgblock_V_12_out_ap_vld,
        imgblock_V_9_out,
        imgblock_V_9_out_ap_vld,
        imgblock_V_8_out,
        imgblock_V_8_out_ap_vld,
        imgblock_V_5_out,
        imgblock_V_5_out_ap_vld
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [9:0] gain_out_data240_dout;
input  [1:0] gain_out_data240_num_data_valid;
input  [1:0] gain_out_data240_fifo_cap;
input   gain_out_data240_empty_n;
output   gain_out_data240_read;
output  [29:0] demosaic_out_data241_din;
input  [1:0] demosaic_out_data241_num_data_valid;
input  [1:0] demosaic_out_data241_fifo_cap;
input   demosaic_out_data241_full_n;
output   demosaic_out_data241_write;
input  [9:0] p_Val2_18;
input  [9:0] imgblock_V_17_1_reload;
input  [9:0] p_Val2_21;
input  [9:0] p_Val2_17;
input  [9:0] imgblock_V_12_1_reload;
input  [9:0] imgblock_V_11_1_reload;
input  [9:0] p_Val2_16;
input  [9:0] imgblock_V_7_1_reload;
input  [9:0] p_Val2_22;
input  [9:0] p_Val2_20;
input  [9:0] p_Val2_19;
input  [9:0] p_Val2_s;
input  [10:0] p_read1;
input  [0:0] trunc_ln;
output  [10:0] linebuffer_V_address0;
output   linebuffer_V_ce0;
output   linebuffer_V_we0;
output  [9:0] linebuffer_V_d0;
output  [10:0] linebuffer_V_address1;
output   linebuffer_V_ce1;
input  [9:0] linebuffer_V_q1;
output  [10:0] linebuffer_V_1_address0;
output   linebuffer_V_1_ce0;
output   linebuffer_V_1_we0;
output  [9:0] linebuffer_V_1_d0;
output  [10:0] linebuffer_V_1_address1;
output   linebuffer_V_1_ce1;
input  [9:0] linebuffer_V_1_q1;
output  [10:0] linebuffer_V_2_address0;
output   linebuffer_V_2_ce0;
output   linebuffer_V_2_we0;
output  [9:0] linebuffer_V_2_d0;
output  [10:0] linebuffer_V_2_address1;
output   linebuffer_V_2_ce1;
input  [9:0] linebuffer_V_2_q1;
output  [10:0] linebuffer_V_3_address0;
output   linebuffer_V_3_ce0;
output   linebuffer_V_3_we0;
output  [9:0] linebuffer_V_3_d0;
output  [10:0] linebuffer_V_3_address1;
output   linebuffer_V_3_ce1;
input  [9:0] linebuffer_V_3_q1;
input  [1:0] line0_V_1;
input  [1:0] line1_V;
input  [1:0] line2_V;
input  [1:0] line3_V;
input  [1:0] lineStore_1_cast;
input  [11:0] sub219;
input  [0:0] cmp162;
output  [9:0] imgblock_V_12_out;
output   imgblock_V_12_out_ap_vld;
output  [9:0] imgblock_V_9_out;
output   imgblock_V_9_out_ap_vld;
output  [9:0] imgblock_V_8_out;
output   imgblock_V_8_out_ap_vld;
output  [9:0] imgblock_V_5_out;
output   imgblock_V_5_out_ap_vld;

reg ap_idle;
reg gain_out_data240_read;
reg demosaic_out_data241_write;
reg linebuffer_V_ce0;
reg linebuffer_V_we0;
reg linebuffer_V_ce1;
reg linebuffer_V_1_ce0;
reg linebuffer_V_1_we0;
reg linebuffer_V_1_ce1;
reg linebuffer_V_2_ce0;
reg linebuffer_V_2_we0;
reg linebuffer_V_2_ce1;
reg linebuffer_V_3_ce0;
reg linebuffer_V_3_we0;
reg linebuffer_V_3_ce1;
reg imgblock_V_12_out_ap_vld;
reg imgblock_V_9_out_ap_vld;
reg imgblock_V_8_out_ap_vld;
reg imgblock_V_5_out_ap_vld;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_enable_reg_pp0_iter3;
reg    ap_enable_reg_pp0_iter4;
reg    ap_enable_reg_pp0_iter5;
reg    ap_enable_reg_pp0_iter6;
reg    ap_enable_reg_pp0_iter7;
reg    ap_idle_pp0;
wire    ap_block_state1_pp0_stage0_iter0;
reg   [0:0] icmp_ln344_reg_1232;
reg    ap_predicate_op99_read_state2;
reg    ap_block_state2_pp0_stage0_iter1;
wire    ap_block_state3_pp0_stage0_iter2;
wire    ap_block_state4_pp0_stage0_iter3;
wire    ap_block_state5_pp0_stage0_iter4;
wire    ap_block_state6_pp0_stage0_iter5;
wire    ap_block_state7_pp0_stage0_iter6;
reg    ap_block_state8_pp0_stage0_iter7;
reg    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln344_fu_736_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
reg    demosaic_out_data241_blk_n;
wire    ap_block_pp0_stage0;
reg    gain_out_data240_blk_n;
reg    ap_block_pp0_stage0_11001;
wire   [12:0] grp_g_kernel_ap_uint_10_5_s_fu_586_ap_return;
reg   [12:0] reg_635;
reg   [0:0] icmp_ln344_reg_1232_pp0_iter4_reg;
reg   [0:0] trunc_ln135_reg_1260;
reg   [0:0] trunc_ln135_reg_1260_pp0_iter4_reg;
wire   [12:0] grp_rgb_bgr_kernel_ap_uint_10_5_s_fu_601_ap_return;
reg   [12:0] reg_641;
wire   [12:0] grp_rgr_bgb_kernel_ap_uint_10_5_s_fu_618_ap_return;
reg   [12:0] reg_647;
wire   [12:0] grp_rb_kernel_ap_uint_10_5_s_fu_571_ap_return;
reg   [0:0] icmp_ln344_reg_1232_pp0_iter5_reg;
reg   [0:0] trunc_ln135_reg_1260_pp0_iter5_reg;
wire   [0:0] cmp162_read_read_fu_204_p2;
reg   [10:0] col_1_reg_1227;
reg   [10:0] col_1_reg_1227_pp0_iter1_reg;
reg   [0:0] icmp_ln344_reg_1232_pp0_iter1_reg;
reg   [0:0] icmp_ln344_reg_1232_pp0_iter2_reg;
reg   [0:0] icmp_ln344_reg_1232_pp0_iter3_reg;
wire   [0:0] icmp_ln373_fu_748_p2;
reg   [0:0] icmp_ln373_reg_1236;
reg   [0:0] icmp_ln373_reg_1236_pp0_iter1_reg;
wire   [0:0] trunc_ln135_fu_774_p1;
reg   [0:0] trunc_ln135_reg_1260_pp0_iter1_reg;
reg   [0:0] trunc_ln135_reg_1260_pp0_iter2_reg;
reg   [0:0] trunc_ln135_reg_1260_pp0_iter3_reg;
wire   [9:0] packed_read1_V_fu_788_p6;
wire   [9:0] packed_read2_V_fu_801_p6;
wire   [9:0] packed_read3_V_fu_814_p6;
wire   [9:0] packed_read4_V_fu_827_p6;
reg   [9:0] imgblock_V_12_reg_1295;
reg   [9:0] imgblock_V_12_reg_1295_pp0_iter3_reg;
reg   [9:0] imgblock_V_12_reg_1295_pp0_iter4_reg;
reg   [9:0] imgblock_V_12_reg_1295_pp0_iter5_reg;
reg   [9:0] r_3_reg_1302;
reg   [9:0] r_3_reg_1302_pp0_iter3_reg;
reg   [9:0] r_3_reg_1302_pp0_iter4_reg;
reg   [9:0] r_3_reg_1302_pp0_iter5_reg;
wire   [12:0] zext_ln124_fu_981_p1;
reg    ap_condition_exit_pp0_iter2_stage0;
reg    grp_rb_kernel_ap_uint_10_5_s_fu_571_ap_ce;
reg    ap_predicate_op148_call_state3;
reg    ap_predicate_op155_call_state3;
wire    ap_block_state1_pp0_stage0_iter0_ignore_call0;
reg    ap_block_state2_pp0_stage0_iter1_ignore_call0;
wire    ap_block_state3_pp0_stage0_iter2_ignore_call0;
wire    ap_block_state4_pp0_stage0_iter3_ignore_call0;
wire    ap_block_state5_pp0_stage0_iter4_ignore_call0;
wire    ap_block_state6_pp0_stage0_iter5_ignore_call0;
wire    ap_block_state7_pp0_stage0_iter6_ignore_call0;
reg    ap_block_state8_pp0_stage0_iter7_ignore_call0;
reg    ap_block_pp0_stage0_11001_ignoreCallOp148;
reg    grp_g_kernel_ap_uint_10_5_s_fu_586_ap_ce;
reg    ap_predicate_op149_call_state3;
reg    ap_predicate_op154_call_state3;
wire    ap_block_state1_pp0_stage0_iter0_ignore_call1;
reg    ap_block_state2_pp0_stage0_iter1_ignore_call1;
wire    ap_block_state3_pp0_stage0_iter2_ignore_call1;
wire    ap_block_state4_pp0_stage0_iter3_ignore_call1;
wire    ap_block_state5_pp0_stage0_iter4_ignore_call1;
wire    ap_block_state6_pp0_stage0_iter5_ignore_call1;
wire    ap_block_state7_pp0_stage0_iter6_ignore_call1;
reg    ap_block_state8_pp0_stage0_iter7_ignore_call1;
reg    ap_block_pp0_stage0_11001_ignoreCallOp149;
reg    grp_rgb_bgr_kernel_ap_uint_10_5_s_fu_601_ap_ce;
reg    ap_predicate_op150_call_state3;
reg    ap_predicate_op153_call_state3;
reg    ap_block_pp0_stage0_11001_ignoreCallOp150;
reg    grp_rgr_bgb_kernel_ap_uint_10_5_s_fu_618_ap_ce;
reg    ap_predicate_op151_call_state3;
reg    ap_predicate_op152_call_state3;
reg    ap_block_pp0_stage0_11001_ignoreCallOp151;
wire   [9:0] ap_phi_reg_pp0_iter0_p_Val2_27_reg_471;
reg   [9:0] ap_phi_reg_pp0_iter1_p_Val2_27_reg_471;
reg   [9:0] ap_phi_reg_pp0_iter2_p_Val2_27_reg_471;
wire   [9:0] ap_phi_reg_pp0_iter0_imgblock_V_14_1_reg_487;
reg   [9:0] ap_phi_reg_pp0_iter1_imgblock_V_14_1_reg_487;
reg   [9:0] ap_phi_reg_pp0_iter2_imgblock_V_14_1_reg_487;
wire   [9:0] ap_phi_reg_pp0_iter0_empty_reg_499;
reg   [9:0] ap_phi_reg_pp0_iter1_empty_reg_499;
reg   [9:0] ap_phi_reg_pp0_iter2_empty_reg_499;
wire   [9:0] ap_phi_reg_pp0_iter0_empty_104_reg_510;
reg   [9:0] ap_phi_reg_pp0_iter1_empty_104_reg_510;
reg   [9:0] ap_phi_reg_pp0_iter2_empty_104_reg_510;
wire   [9:0] ap_phi_reg_pp0_iter0_empty_105_reg_521;
reg   [9:0] ap_phi_reg_pp0_iter1_empty_105_reg_521;
reg   [9:0] ap_phi_reg_pp0_iter2_empty_105_reg_521;
wire   [12:0] ap_phi_reg_pp0_iter0_b_5_reg_532;
reg   [12:0] ap_phi_reg_pp0_iter1_b_5_reg_532;
reg   [12:0] ap_phi_reg_pp0_iter2_b_5_reg_532;
reg   [12:0] ap_phi_reg_pp0_iter3_b_5_reg_532;
reg   [12:0] ap_phi_reg_pp0_iter4_b_5_reg_532;
reg   [12:0] ap_phi_reg_pp0_iter5_b_5_reg_532;
reg   [12:0] ap_phi_reg_pp0_iter6_b_5_reg_532;
reg   [12:0] ap_phi_reg_pp0_iter7_b_5_reg_532;
wire   [12:0] ap_phi_reg_pp0_iter0_g_4_reg_545;
reg   [12:0] ap_phi_reg_pp0_iter1_g_4_reg_545;
reg   [12:0] ap_phi_reg_pp0_iter2_g_4_reg_545;
reg   [12:0] ap_phi_reg_pp0_iter3_g_4_reg_545;
reg   [12:0] ap_phi_reg_pp0_iter4_g_4_reg_545;
reg   [12:0] ap_phi_reg_pp0_iter5_g_4_reg_545;
reg   [12:0] ap_phi_reg_pp0_iter6_g_4_reg_545;
reg   [12:0] ap_phi_reg_pp0_iter7_g_4_reg_545;
wire   [12:0] ap_phi_reg_pp0_iter0_r_5_reg_558;
reg   [12:0] ap_phi_reg_pp0_iter1_r_5_reg_558;
reg   [12:0] ap_phi_reg_pp0_iter2_r_5_reg_558;
reg   [12:0] ap_phi_reg_pp0_iter3_r_5_reg_558;
reg   [12:0] ap_phi_reg_pp0_iter4_r_5_reg_558;
reg   [12:0] ap_phi_reg_pp0_iter5_r_5_reg_558;
reg   [12:0] ap_phi_reg_pp0_iter6_r_5_reg_558;
reg   [12:0] ap_phi_reg_pp0_iter7_r_5_reg_558;
wire   [63:0] zext_ln344_2_fu_757_p1;
wire   [63:0] zext_ln344_fu_870_p1;
reg   [10:0] col_fu_148;
wire   [10:0] add_ln344_fu_742_p2;
wire    ap_loop_init;
reg   [10:0] ap_sig_allocacmp_col_1;
reg   [11:0] bram_read_count_fu_152;
wire   [11:0] add_ln406_fu_768_p2;
reg   [11:0] ap_sig_allocacmp_bram_read_count_load_1;
reg   [11:0] ap_sig_allocacmp_bram_read_count_load;
reg   [9:0] imgblock_V_fu_156;
reg   [9:0] imgblock_V_1_fu_160;
reg   [9:0] imgblock_V_2_fu_164;
reg   [9:0] imgblock_V_3_fu_168;
reg   [9:0] imgblock_V_4_fu_172;
reg   [9:0] imgblock_V_5_fu_176;
reg   [9:0] ret_fu_180;
reg   [9:0] imgblock_V_6_fu_184;
reg   [9:0] imgblock_V_7_fu_188;
reg   [9:0] imgblock_V_8_fu_192;
reg   [9:0] imgblock_V_9_fu_196;
reg   [9:0] imgblock_V_10_fu_200;
reg    ap_block_pp0_stage0_01001;
wire   [11:0] zext_ln344_1_fu_732_p1;
wire   [2:0] tmp_fu_984_p4;
wire   [0:0] icmp_ln40_fu_994_p2;
wire   [9:0] trunc_ln260_fu_1000_p1;
wire   [2:0] tmp_47_fu_1012_p4;
wire   [0:0] icmp_ln40_1_fu_1022_p2;
wire   [9:0] trunc_ln260_3_fu_1028_p1;
wire   [2:0] tmp_48_fu_1040_p4;
wire   [0:0] icmp_ln40_2_fu_1050_p2;
wire   [9:0] trunc_ln260_4_fu_1056_p1;
wire   [9:0] select_ln40_2_fu_1060_p3;
wire   [9:0] select_ln40_1_fu_1032_p3;
wire   [9:0] select_ln40_fu_1004_p3;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg    ap_loop_exit_ready_pp0_iter1_reg;
reg    ap_loop_exit_ready_pp0_iter2_reg;
reg    ap_loop_exit_ready_pp0_iter3_reg;
reg    ap_loop_exit_ready_pp0_iter4_reg;
reg    ap_loop_exit_ready_pp0_iter5_reg;
reg    ap_loop_exit_ready_pp0_iter6_reg;
reg   [0:0] ap_NS_fsm;
reg    ap_block_pp0;
reg    ap_predicate_op86_load_state1;
reg    ap_enable_operation_86;
reg    ap_enable_state1_pp0_iter0_stage0;
reg    ap_predicate_op101_load_state2;
reg    ap_enable_operation_101;
reg    ap_enable_state2_pp0_iter1_stage0;
reg    ap_predicate_op126_store_state3;
reg    ap_enable_operation_126;
reg    ap_enable_state3_pp0_iter2_stage0;
reg    ap_predicate_op134_store_state3;
reg    ap_enable_operation_134;
reg    ap_predicate_op87_load_state1;
reg    ap_enable_operation_87;
reg    ap_predicate_op102_load_state2;
reg    ap_enable_operation_102;
reg    ap_predicate_op124_store_state3;
reg    ap_enable_operation_124;
reg    ap_predicate_op132_store_state3;
reg    ap_enable_operation_132;
reg    ap_predicate_op88_load_state1;
reg    ap_enable_operation_88;
reg    ap_predicate_op103_load_state2;
reg    ap_enable_operation_103;
reg    ap_predicate_op122_store_state3;
reg    ap_enable_operation_122;
reg    ap_predicate_op130_store_state3;
reg    ap_enable_operation_130;
reg    ap_predicate_op89_load_state1;
reg    ap_enable_operation_89;
reg    ap_predicate_op104_load_state2;
reg    ap_enable_operation_104;
reg    ap_predicate_op128_store_state3;
reg    ap_enable_operation_128;
reg    ap_predicate_op136_store_state3;
reg    ap_enable_operation_136;
wire    ap_enable_pp0;
wire    ap_start_int;
reg    ap_condition_660;
reg    ap_condition_662;
reg    ap_condition_238;
reg    ap_condition_702;
reg    ap_condition_704;
reg    ap_condition_242;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
#0 ap_enable_reg_pp0_iter4 = 1'b0;
#0 ap_enable_reg_pp0_iter5 = 1'b0;
#0 ap_enable_reg_pp0_iter6 = 1'b0;
#0 ap_enable_reg_pp0_iter7 = 1'b0;
#0 ap_done_reg = 1'b0;
end

ISPPipeline_accel_rb_kernel_ap_uint_10_5_s grp_rb_kernel_ap_uint_10_5_s_fu_571(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .p_read(imgblock_V_fu_156),
    .p_read1(imgblock_V_3_fu_168),
    .p_read2(imgblock_V_1_fu_160),
    .p_read3(imgblock_V_4_fu_172),
    .p_read4(imgblock_V_8_fu_192),
    .p_read5(ap_phi_reg_pp0_iter2_imgblock_V_14_1_reg_487),
    .p_read6(imgblock_V_5_fu_176),
    .p_read7(imgblock_V_2_fu_164),
    .p_read8(ap_phi_reg_pp0_iter2_p_Val2_27_reg_471),
    .ap_return(grp_rb_kernel_ap_uint_10_5_s_fu_571_ap_return),
    .ap_ce(grp_rb_kernel_ap_uint_10_5_s_fu_571_ap_ce)
);

ISPPipeline_accel_g_kernel_ap_uint_10_5_s grp_g_kernel_ap_uint_10_5_s_fu_586(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .p_read(imgblock_V_fu_156),
    .p_read1(imgblock_V_6_fu_184),
    .p_read2(imgblock_V_4_fu_172),
    .p_read3(imgblock_V_7_fu_188),
    .p_read4(imgblock_V_8_fu_192),
    .p_read5(imgblock_V_9_fu_196),
    .p_read6(ap_phi_reg_pp0_iter2_imgblock_V_14_1_reg_487),
    .p_read7(imgblock_V_10_fu_200),
    .p_read8(ap_phi_reg_pp0_iter2_p_Val2_27_reg_471),
    .ap_return(grp_g_kernel_ap_uint_10_5_s_fu_586_ap_return),
    .ap_ce(grp_g_kernel_ap_uint_10_5_s_fu_586_ap_ce)
);

ISPPipeline_accel_rgb_bgr_kernel_ap_uint_10_5_s grp_rgb_bgr_kernel_ap_uint_10_5_s_fu_601(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .p_read(imgblock_V_fu_156),
    .p_read1(imgblock_V_3_fu_168),
    .p_read2(imgblock_V_6_fu_184),
    .p_read3(imgblock_V_1_fu_160),
    .p_read4(imgblock_V_4_fu_172),
    .p_read5(imgblock_V_8_fu_192),
    .p_read6(ap_phi_reg_pp0_iter2_imgblock_V_14_1_reg_487),
    .p_read7(imgblock_V_5_fu_176),
    .p_read8(imgblock_V_10_fu_200),
    .p_read9(imgblock_V_2_fu_164),
    .p_read10(ap_phi_reg_pp0_iter2_p_Val2_27_reg_471),
    .ap_return(grp_rgb_bgr_kernel_ap_uint_10_5_s_fu_601_ap_return),
    .ap_ce(grp_rgb_bgr_kernel_ap_uint_10_5_s_fu_601_ap_ce)
);

ISPPipeline_accel_rgr_bgb_kernel_ap_uint_10_5_s grp_rgr_bgb_kernel_ap_uint_10_5_s_fu_618(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .p_read(imgblock_V_fu_156),
    .p_read1(imgblock_V_3_fu_168),
    .p_read2(imgblock_V_1_fu_160),
    .p_read3(imgblock_V_4_fu_172),
    .p_read4(imgblock_V_7_fu_188),
    .p_read5(imgblock_V_8_fu_192),
    .p_read6(imgblock_V_9_fu_196),
    .p_read7(ap_phi_reg_pp0_iter2_imgblock_V_14_1_reg_487),
    .p_read8(imgblock_V_5_fu_176),
    .p_read9(imgblock_V_2_fu_164),
    .p_read10(ap_phi_reg_pp0_iter2_p_Val2_27_reg_471),
    .ap_return(grp_rgr_bgb_kernel_ap_uint_10_5_s_fu_618_ap_return),
    .ap_ce(grp_rgr_bgb_kernel_ap_uint_10_5_s_fu_618_ap_ce)
);

ISPPipeline_accel_mux_42_10_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 10 ),
    .din1_WIDTH( 10 ),
    .din2_WIDTH( 10 ),
    .din3_WIDTH( 10 ),
    .din4_WIDTH( 2 ),
    .dout_WIDTH( 10 ))
mux_42_10_1_1_U140(
    .din0(linebuffer_V_q1),
    .din1(linebuffer_V_1_q1),
    .din2(linebuffer_V_2_q1),
    .din3(linebuffer_V_3_q1),
    .din4(line0_V_1),
    .dout(packed_read1_V_fu_788_p6)
);

ISPPipeline_accel_mux_42_10_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 10 ),
    .din1_WIDTH( 10 ),
    .din2_WIDTH( 10 ),
    .din3_WIDTH( 10 ),
    .din4_WIDTH( 2 ),
    .dout_WIDTH( 10 ))
mux_42_10_1_1_U141(
    .din0(linebuffer_V_q1),
    .din1(linebuffer_V_1_q1),
    .din2(linebuffer_V_2_q1),
    .din3(linebuffer_V_3_q1),
    .din4(line1_V),
    .dout(packed_read2_V_fu_801_p6)
);

ISPPipeline_accel_mux_42_10_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 10 ),
    .din1_WIDTH( 10 ),
    .din2_WIDTH( 10 ),
    .din3_WIDTH( 10 ),
    .din4_WIDTH( 2 ),
    .dout_WIDTH( 10 ))
mux_42_10_1_1_U142(
    .din0(linebuffer_V_q1),
    .din1(linebuffer_V_1_q1),
    .din2(linebuffer_V_2_q1),
    .din3(linebuffer_V_3_q1),
    .din4(line2_V),
    .dout(packed_read3_V_fu_814_p6)
);

ISPPipeline_accel_mux_42_10_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 10 ),
    .din1_WIDTH( 10 ),
    .din2_WIDTH( 10 ),
    .din3_WIDTH( 10 ),
    .din4_WIDTH( 2 ),
    .dout_WIDTH( 10 ))
mux_42_10_1_1_U143(
    .din0(linebuffer_V_q1),
    .din1(linebuffer_V_1_q1),
    .din2(linebuffer_V_2_q1),
    .din3(linebuffer_V_3_q1),
    .din4(line3_V),
    .dout(packed_read4_V_fu_827_p6)
);

ISPPipeline_accel_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter6_reg == 1'b1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter2_stage0)) begin
            ap_enable_reg_pp0_iter3 <= 1'b0;
        end else if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter4 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter5 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter5 <= ap_enable_reg_pp0_iter4;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter6 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter6 <= ap_enable_reg_pp0_iter5;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter7 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter7 <= ap_enable_reg_pp0_iter6;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_660)) begin
        if (((icmp_ln344_fu_736_p2 == 1'd0) & (icmp_ln373_fu_748_p2 == 1'd0))) begin
            ap_phi_reg_pp0_iter1_empty_104_reg_510 <= 10'd0;
        end else if ((1'b1 == 1'b1)) begin
            ap_phi_reg_pp0_iter1_empty_104_reg_510 <= ap_phi_reg_pp0_iter0_empty_104_reg_510;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_660)) begin
        if (((icmp_ln344_fu_736_p2 == 1'd0) & (icmp_ln373_fu_748_p2 == 1'd0))) begin
            ap_phi_reg_pp0_iter1_empty_105_reg_521 <= 10'd0;
        end else if ((1'b1 == 1'b1)) begin
            ap_phi_reg_pp0_iter1_empty_105_reg_521 <= ap_phi_reg_pp0_iter0_empty_105_reg_521;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_660)) begin
        if (((icmp_ln344_fu_736_p2 == 1'd0) & (icmp_ln373_fu_748_p2 == 1'd0))) begin
            ap_phi_reg_pp0_iter1_empty_reg_499 <= 10'd0;
        end else if ((1'b1 == 1'b1)) begin
            ap_phi_reg_pp0_iter1_empty_reg_499 <= ap_phi_reg_pp0_iter0_empty_reg_499;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_660)) begin
        if (((icmp_ln344_fu_736_p2 == 1'd0) & (icmp_ln373_fu_748_p2 == 1'd0))) begin
            ap_phi_reg_pp0_iter1_imgblock_V_14_1_reg_487 <= 10'd0;
        end else if ((1'b1 == 1'b1)) begin
            ap_phi_reg_pp0_iter1_imgblock_V_14_1_reg_487 <= ap_phi_reg_pp0_iter0_imgblock_V_14_1_reg_487;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_660)) begin
        if (((icmp_ln344_fu_736_p2 == 1'd0) & (cmp162_read_read_fu_204_p2 == 1'd0))) begin
            ap_phi_reg_pp0_iter1_p_Val2_27_reg_471 <= 10'd0;
        end else if ((1'b1 == 1'b1)) begin
            ap_phi_reg_pp0_iter1_p_Val2_27_reg_471 <= ap_phi_reg_pp0_iter0_p_Val2_27_reg_471;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_662)) begin
        if (((icmp_ln344_reg_1232 == 1'd0) & (icmp_ln373_reg_1236 == 1'd1))) begin
            ap_phi_reg_pp0_iter2_empty_104_reg_510 <= packed_read2_V_fu_801_p6;
        end else if ((1'b1 == 1'b1)) begin
            ap_phi_reg_pp0_iter2_empty_104_reg_510 <= ap_phi_reg_pp0_iter1_empty_104_reg_510;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_662)) begin
        if (((icmp_ln344_reg_1232 == 1'd0) & (icmp_ln373_reg_1236 == 1'd1))) begin
            ap_phi_reg_pp0_iter2_empty_105_reg_521 <= packed_read1_V_fu_788_p6;
        end else if ((1'b1 == 1'b1)) begin
            ap_phi_reg_pp0_iter2_empty_105_reg_521 <= ap_phi_reg_pp0_iter1_empty_105_reg_521;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_662)) begin
        if (((icmp_ln344_reg_1232 == 1'd0) & (icmp_ln373_reg_1236 == 1'd1))) begin
            ap_phi_reg_pp0_iter2_empty_reg_499 <= packed_read4_V_fu_827_p6;
        end else if ((1'b1 == 1'b1)) begin
            ap_phi_reg_pp0_iter2_empty_reg_499 <= ap_phi_reg_pp0_iter1_empty_reg_499;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_662)) begin
        if (((icmp_ln344_reg_1232 == 1'd0) & (icmp_ln373_reg_1236 == 1'd1))) begin
            ap_phi_reg_pp0_iter2_imgblock_V_14_1_reg_487 <= packed_read3_V_fu_814_p6;
        end else if ((1'b1 == 1'b1)) begin
            ap_phi_reg_pp0_iter2_imgblock_V_14_1_reg_487 <= ap_phi_reg_pp0_iter1_imgblock_V_14_1_reg_487;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_662)) begin
        if (((cmp162 == 1'd1) & (icmp_ln344_reg_1232 == 1'd0))) begin
            ap_phi_reg_pp0_iter2_p_Val2_27_reg_471 <= gain_out_data240_dout;
        end else if ((1'b1 == 1'b1)) begin
            ap_phi_reg_pp0_iter2_p_Val2_27_reg_471 <= ap_phi_reg_pp0_iter1_p_Val2_27_reg_471;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter6 == 1'b1))) begin
        if ((1'b1 == ap_condition_242)) begin
            ap_phi_reg_pp0_iter7_b_5_reg_532 <= zext_ln124_fu_981_p1;
        end else if ((1'b1 == ap_condition_704)) begin
            ap_phi_reg_pp0_iter7_b_5_reg_532 <= reg_647;
        end else if ((1'b1 == ap_condition_702)) begin
            ap_phi_reg_pp0_iter7_b_5_reg_532 <= reg_641;
        end else if ((1'b1 == ap_condition_238)) begin
            ap_phi_reg_pp0_iter7_b_5_reg_532 <= grp_rb_kernel_ap_uint_10_5_s_fu_571_ap_return;
        end else if ((1'b1 == 1'b1)) begin
            ap_phi_reg_pp0_iter7_b_5_reg_532 <= ap_phi_reg_pp0_iter6_b_5_reg_532;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter6 == 1'b1) & (trunc_ln135_reg_1260_pp0_iter5_reg == 1'd1) & (icmp_ln344_reg_1232_pp0_iter5_reg == 1'd0) & (trunc_ln == 1'd0)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter6 == 1'b1) & (trunc_ln135_reg_1260_pp0_iter5_reg == 1'd0) & (icmp_ln344_reg_1232_pp0_iter5_reg == 1'd0) & (trunc_ln == 1'd1)))) begin
        ap_phi_reg_pp0_iter7_g_4_reg_545 <= zext_ln124_fu_981_p1;
    end else if ((((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter6 == 1'b1) & (trunc_ln135_reg_1260_pp0_iter5_reg == 1'd1) & (icmp_ln344_reg_1232_pp0_iter5_reg == 1'd0) & (trunc_ln == 1'd1)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter6 == 1'b1) & (trunc_ln135_reg_1260_pp0_iter5_reg == 1'd0) & (icmp_ln344_reg_1232_pp0_iter5_reg == 1'd0) & (trunc_ln == 1'd0)))) begin
        ap_phi_reg_pp0_iter7_g_4_reg_545 <= reg_635;
    end else if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter6 == 1'b1))) begin
        ap_phi_reg_pp0_iter7_g_4_reg_545 <= ap_phi_reg_pp0_iter6_g_4_reg_545;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter6 == 1'b1))) begin
        if ((1'b1 == ap_condition_242)) begin
            ap_phi_reg_pp0_iter7_r_5_reg_558 <= grp_rb_kernel_ap_uint_10_5_s_fu_571_ap_return;
        end else if ((1'b1 == ap_condition_704)) begin
            ap_phi_reg_pp0_iter7_r_5_reg_558 <= reg_641;
        end else if ((1'b1 == ap_condition_702)) begin
            ap_phi_reg_pp0_iter7_r_5_reg_558 <= reg_647;
        end else if ((1'b1 == ap_condition_238)) begin
            ap_phi_reg_pp0_iter7_r_5_reg_558 <= zext_ln124_fu_981_p1;
        end else if ((1'b1 == 1'b1)) begin
            ap_phi_reg_pp0_iter7_r_5_reg_558 <= ap_phi_reg_pp0_iter6_r_5_reg_558;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln344_fu_736_p2 == 1'd0) & (ap_start_int == 1'b1))) begin
            bram_read_count_fu_152 <= add_ln406_fu_768_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            bram_read_count_fu_152 <= 12'd2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln344_fu_736_p2 == 1'd0) & (ap_start_int == 1'b1))) begin
            col_fu_148 <= add_ln344_fu_742_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            col_fu_148 <= 11'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            imgblock_V_10_fu_200 <= p_Val2_18;
        end else if (((icmp_ln344_reg_1232_pp0_iter1_reg == 1'd0) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
            imgblock_V_10_fu_200 <= imgblock_V_2_fu_164;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            imgblock_V_1_fu_160 <= p_Val2_20;
        end else if (((icmp_ln344_reg_1232_pp0_iter1_reg == 1'd0) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
            imgblock_V_1_fu_160 <= ap_phi_reg_pp0_iter2_empty_104_reg_510;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            imgblock_V_2_fu_164 <= p_Val2_22;
        end else if (((icmp_ln344_reg_1232_pp0_iter1_reg == 1'd0) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
            imgblock_V_2_fu_164 <= ap_phi_reg_pp0_iter2_empty_reg_499;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            imgblock_V_3_fu_168 <= imgblock_V_7_1_reload;
        end else if (((icmp_ln344_reg_1232_pp0_iter1_reg == 1'd0) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
            imgblock_V_3_fu_168 <= imgblock_V_6_fu_184;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            imgblock_V_4_fu_172 <= imgblock_V_11_1_reload;
        end else if (((icmp_ln344_reg_1232_pp0_iter1_reg == 1'd0) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
            imgblock_V_4_fu_172 <= imgblock_V_7_fu_188;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            imgblock_V_5_fu_176 <= imgblock_V_17_1_reload;
        end else if (((icmp_ln344_reg_1232_pp0_iter1_reg == 1'd0) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
            imgblock_V_5_fu_176 <= imgblock_V_10_fu_200;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            imgblock_V_6_fu_184 <= p_Val2_16;
        end else if (((icmp_ln344_reg_1232_pp0_iter1_reg == 1'd0) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
            imgblock_V_6_fu_184 <= imgblock_V_1_fu_160;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            imgblock_V_7_fu_188 <= imgblock_V_12_1_reload;
        end else if (((icmp_ln344_reg_1232_pp0_iter1_reg == 1'd0) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
            imgblock_V_7_fu_188 <= imgblock_V_8_fu_192;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            imgblock_V_8_fu_192 <= p_Val2_17;
        end else if (((icmp_ln344_reg_1232_pp0_iter1_reg == 1'd0) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
            imgblock_V_8_fu_192 <= imgblock_V_9_fu_196;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            imgblock_V_9_fu_196 <= p_Val2_21;
        end else if (((icmp_ln344_reg_1232_pp0_iter1_reg == 1'd0) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
            imgblock_V_9_fu_196 <= ap_phi_reg_pp0_iter2_imgblock_V_14_1_reg_487;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            imgblock_V_fu_156 <= p_Val2_s;
        end else if (((icmp_ln344_reg_1232_pp0_iter1_reg == 1'd0) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
            imgblock_V_fu_156 <= ret_fu_180;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ret_fu_180 <= p_Val2_19;
        end else if (((icmp_ln344_reg_1232_pp0_iter1_reg == 1'd0) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
            ret_fu_180 <= ap_phi_reg_pp0_iter2_empty_105_reg_521;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
        ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready_pp0_iter1_reg;
        col_1_reg_1227 <= ap_sig_allocacmp_col_1;
        col_1_reg_1227_pp0_iter1_reg <= col_1_reg_1227;
        icmp_ln344_reg_1232 <= icmp_ln344_fu_736_p2;
        icmp_ln344_reg_1232_pp0_iter1_reg <= icmp_ln344_reg_1232;
        icmp_ln373_reg_1236_pp0_iter1_reg <= icmp_ln373_reg_1236;
        trunc_ln135_reg_1260_pp0_iter1_reg <= trunc_ln135_reg_1260;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        ap_loop_exit_ready_pp0_iter3_reg <= ap_loop_exit_ready_pp0_iter2_reg;
        ap_loop_exit_ready_pp0_iter4_reg <= ap_loop_exit_ready_pp0_iter3_reg;
        ap_loop_exit_ready_pp0_iter5_reg <= ap_loop_exit_ready_pp0_iter4_reg;
        ap_loop_exit_ready_pp0_iter6_reg <= ap_loop_exit_ready_pp0_iter5_reg;
        icmp_ln344_reg_1232_pp0_iter2_reg <= icmp_ln344_reg_1232_pp0_iter1_reg;
        icmp_ln344_reg_1232_pp0_iter3_reg <= icmp_ln344_reg_1232_pp0_iter2_reg;
        icmp_ln344_reg_1232_pp0_iter4_reg <= icmp_ln344_reg_1232_pp0_iter3_reg;
        icmp_ln344_reg_1232_pp0_iter5_reg <= icmp_ln344_reg_1232_pp0_iter4_reg;
        imgblock_V_12_reg_1295_pp0_iter3_reg <= imgblock_V_12_reg_1295;
        imgblock_V_12_reg_1295_pp0_iter4_reg <= imgblock_V_12_reg_1295_pp0_iter3_reg;
        imgblock_V_12_reg_1295_pp0_iter5_reg <= imgblock_V_12_reg_1295_pp0_iter4_reg;
        r_3_reg_1302 <= imgblock_V_8_fu_192;
        r_3_reg_1302_pp0_iter3_reg <= r_3_reg_1302;
        r_3_reg_1302_pp0_iter4_reg <= r_3_reg_1302_pp0_iter3_reg;
        r_3_reg_1302_pp0_iter5_reg <= r_3_reg_1302_pp0_iter4_reg;
        trunc_ln135_reg_1260_pp0_iter2_reg <= trunc_ln135_reg_1260_pp0_iter1_reg;
        trunc_ln135_reg_1260_pp0_iter3_reg <= trunc_ln135_reg_1260_pp0_iter2_reg;
        trunc_ln135_reg_1260_pp0_iter4_reg <= trunc_ln135_reg_1260_pp0_iter3_reg;
        trunc_ln135_reg_1260_pp0_iter5_reg <= trunc_ln135_reg_1260_pp0_iter4_reg;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_phi_reg_pp0_iter1_b_5_reg_532 <= ap_phi_reg_pp0_iter0_b_5_reg_532;
        ap_phi_reg_pp0_iter1_g_4_reg_545 <= ap_phi_reg_pp0_iter0_g_4_reg_545;
        ap_phi_reg_pp0_iter1_r_5_reg_558 <= ap_phi_reg_pp0_iter0_r_5_reg_558;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_phi_reg_pp0_iter2_b_5_reg_532 <= ap_phi_reg_pp0_iter1_b_5_reg_532;
        ap_phi_reg_pp0_iter2_g_4_reg_545 <= ap_phi_reg_pp0_iter1_g_4_reg_545;
        ap_phi_reg_pp0_iter2_r_5_reg_558 <= ap_phi_reg_pp0_iter1_r_5_reg_558;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        ap_phi_reg_pp0_iter3_b_5_reg_532 <= ap_phi_reg_pp0_iter2_b_5_reg_532;
        ap_phi_reg_pp0_iter3_g_4_reg_545 <= ap_phi_reg_pp0_iter2_g_4_reg_545;
        ap_phi_reg_pp0_iter3_r_5_reg_558 <= ap_phi_reg_pp0_iter2_r_5_reg_558;
        imgblock_V_12_reg_1295 <= imgblock_V_7_fu_188;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        ap_phi_reg_pp0_iter4_b_5_reg_532 <= ap_phi_reg_pp0_iter3_b_5_reg_532;
        ap_phi_reg_pp0_iter4_g_4_reg_545 <= ap_phi_reg_pp0_iter3_g_4_reg_545;
        ap_phi_reg_pp0_iter4_r_5_reg_558 <= ap_phi_reg_pp0_iter3_r_5_reg_558;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter4 == 1'b1))) begin
        ap_phi_reg_pp0_iter5_b_5_reg_532 <= ap_phi_reg_pp0_iter4_b_5_reg_532;
        ap_phi_reg_pp0_iter5_g_4_reg_545 <= ap_phi_reg_pp0_iter4_g_4_reg_545;
        ap_phi_reg_pp0_iter5_r_5_reg_558 <= ap_phi_reg_pp0_iter4_r_5_reg_558;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter5 == 1'b1))) begin
        ap_phi_reg_pp0_iter6_b_5_reg_532 <= ap_phi_reg_pp0_iter5_b_5_reg_532;
        ap_phi_reg_pp0_iter6_g_4_reg_545 <= ap_phi_reg_pp0_iter5_g_4_reg_545;
        ap_phi_reg_pp0_iter6_r_5_reg_558 <= ap_phi_reg_pp0_iter5_r_5_reg_558;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln344_fu_736_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        icmp_ln373_reg_1236 <= icmp_ln373_fu_748_p2;
        trunc_ln135_reg_1260 <= trunc_ln135_fu_774_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter5 == 1'b1) & (trunc_ln135_reg_1260_pp0_iter4_reg == 1'd1) & (trunc_ln == 1'd1) & (icmp_ln344_reg_1232_pp0_iter4_reg == 1'd0)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter5 == 1'b1) & (trunc_ln135_reg_1260_pp0_iter4_reg == 1'd0) & (trunc_ln == 1'd0) & (icmp_ln344_reg_1232_pp0_iter4_reg == 1'd0)))) begin
        reg_635 <= grp_g_kernel_ap_uint_10_5_s_fu_586_ap_return;
    end
end

always @ (posedge ap_clk) begin
    if ((((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter5 == 1'b1) & (trunc_ln135_reg_1260_pp0_iter4_reg == 1'd1) & (trunc_ln == 1'd0) & (icmp_ln344_reg_1232_pp0_iter4_reg == 1'd0)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter5 == 1'b1) & (trunc_ln135_reg_1260_pp0_iter4_reg == 1'd0) & (trunc_ln == 1'd1) & (icmp_ln344_reg_1232_pp0_iter4_reg == 1'd0)))) begin
        reg_641 <= grp_rgb_bgr_kernel_ap_uint_10_5_s_fu_601_ap_return;
        reg_647 <= grp_rgr_bgb_kernel_ap_uint_10_5_s_fu_618_ap_return;
    end
end

always @ (*) begin
    if (((icmp_ln344_fu_736_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (icmp_ln344_reg_1232_pp0_iter1_reg == 1'd1) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        ap_condition_exit_pp0_iter2_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter2_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter6_reg == 1'b1))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_start_int == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter7 == 1'b0) & (ap_enable_reg_pp0_iter6 == 1'b0) & (ap_enable_reg_pp0_iter5 == 1'b0) & (ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_sig_allocacmp_bram_read_count_load = 12'd2;
    end else begin
        ap_sig_allocacmp_bram_read_count_load = bram_read_count_fu_152;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_sig_allocacmp_bram_read_count_load_1 = 12'd2;
    end else begin
        ap_sig_allocacmp_bram_read_count_load_1 = bram_read_count_fu_152;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_sig_allocacmp_col_1 = 11'd0;
    end else begin
        ap_sig_allocacmp_col_1 = col_fu_148;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter7 == 1'b1))) begin
        demosaic_out_data241_blk_n = demosaic_out_data241_full_n;
    end else begin
        demosaic_out_data241_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter7 == 1'b1))) begin
        demosaic_out_data241_write = 1'b1;
    end else begin
        demosaic_out_data241_write = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_predicate_op99_read_state2 == 1'b1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        gain_out_data240_blk_n = gain_out_data240_empty_n;
    end else begin
        gain_out_data240_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_predicate_op99_read_state2 == 1'b1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        gain_out_data240_read = 1'b1;
    end else begin
        gain_out_data240_read = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001_ignoreCallOp149) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_g_kernel_ap_uint_10_5_s_fu_586_ap_ce = 1'b1;
    end else begin
        grp_g_kernel_ap_uint_10_5_s_fu_586_ap_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001_ignoreCallOp148) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_rb_kernel_ap_uint_10_5_s_fu_571_ap_ce = 1'b1;
    end else begin
        grp_rb_kernel_ap_uint_10_5_s_fu_571_ap_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001_ignoreCallOp150) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_rgb_bgr_kernel_ap_uint_10_5_s_fu_601_ap_ce = 1'b1;
    end else begin
        grp_rgb_bgr_kernel_ap_uint_10_5_s_fu_601_ap_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001_ignoreCallOp151) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_rgr_bgb_kernel_ap_uint_10_5_s_fu_618_ap_ce = 1'b1;
    end else begin
        grp_rgr_bgb_kernel_ap_uint_10_5_s_fu_618_ap_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln344_reg_1232_pp0_iter5_reg == 1'd1))) begin
        imgblock_V_12_out_ap_vld = 1'b1;
    end else begin
        imgblock_V_12_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln344_reg_1232_pp0_iter5_reg == 1'd1))) begin
        imgblock_V_5_out_ap_vld = 1'b1;
    end else begin
        imgblock_V_5_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln344_reg_1232_pp0_iter5_reg == 1'd1))) begin
        imgblock_V_8_out_ap_vld = 1'b1;
    end else begin
        imgblock_V_8_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln344_reg_1232_pp0_iter5_reg == 1'd1))) begin
        imgblock_V_9_out_ap_vld = 1'b1;
    end else begin
        imgblock_V_9_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln373_reg_1236_pp0_iter1_reg == 1'd1) & (icmp_ln344_reg_1232_pp0_iter1_reg == 1'd0) & (lineStore_1_cast == 2'd1) & (ap_enable_reg_pp0_iter2 == 1'b1)) | ((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln373_reg_1236_pp0_iter1_reg == 1'd0) & (icmp_ln344_reg_1232_pp0_iter1_reg == 1'd0) & (lineStore_1_cast == 2'd1) & (ap_enable_reg_pp0_iter2 == 1'b1)))) begin
        linebuffer_V_1_ce0 = 1'b1;
    end else begin
        linebuffer_V_1_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        linebuffer_V_1_ce1 = 1'b1;
    end else begin
        linebuffer_V_1_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln373_reg_1236_pp0_iter1_reg == 1'd1) & (icmp_ln344_reg_1232_pp0_iter1_reg == 1'd0) & (lineStore_1_cast == 2'd1) & (ap_enable_reg_pp0_iter2 == 1'b1)) | ((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln373_reg_1236_pp0_iter1_reg == 1'd0) & (icmp_ln344_reg_1232_pp0_iter1_reg == 1'd0) & (lineStore_1_cast == 2'd1) & (ap_enable_reg_pp0_iter2 == 1'b1)))) begin
        linebuffer_V_1_we0 = 1'b1;
    end else begin
        linebuffer_V_1_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln373_reg_1236_pp0_iter1_reg == 1'd1) & (icmp_ln344_reg_1232_pp0_iter1_reg == 1'd0) & (lineStore_1_cast == 2'd2) & (ap_enable_reg_pp0_iter2 == 1'b1)) | ((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln373_reg_1236_pp0_iter1_reg == 1'd0) & (icmp_ln344_reg_1232_pp0_iter1_reg == 1'd0) & (lineStore_1_cast == 2'd2) & (ap_enable_reg_pp0_iter2 == 1'b1)))) begin
        linebuffer_V_2_ce0 = 1'b1;
    end else begin
        linebuffer_V_2_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        linebuffer_V_2_ce1 = 1'b1;
    end else begin
        linebuffer_V_2_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln373_reg_1236_pp0_iter1_reg == 1'd1) & (icmp_ln344_reg_1232_pp0_iter1_reg == 1'd0) & (lineStore_1_cast == 2'd2) & (ap_enable_reg_pp0_iter2 == 1'b1)) | ((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln373_reg_1236_pp0_iter1_reg == 1'd0) & (icmp_ln344_reg_1232_pp0_iter1_reg == 1'd0) & (lineStore_1_cast == 2'd2) & (ap_enable_reg_pp0_iter2 == 1'b1)))) begin
        linebuffer_V_2_we0 = 1'b1;
    end else begin
        linebuffer_V_2_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln373_reg_1236_pp0_iter1_reg == 1'd1) & (icmp_ln344_reg_1232_pp0_iter1_reg == 1'd0) & (lineStore_1_cast == 2'd3) & (ap_enable_reg_pp0_iter2 == 1'b1)) | ((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln373_reg_1236_pp0_iter1_reg == 1'd0) & (icmp_ln344_reg_1232_pp0_iter1_reg == 1'd0) & (lineStore_1_cast == 2'd3) & (ap_enable_reg_pp0_iter2 == 1'b1)))) begin
        linebuffer_V_3_ce0 = 1'b1;
    end else begin
        linebuffer_V_3_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        linebuffer_V_3_ce1 = 1'b1;
    end else begin
        linebuffer_V_3_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln373_reg_1236_pp0_iter1_reg == 1'd1) & (icmp_ln344_reg_1232_pp0_iter1_reg == 1'd0) & (lineStore_1_cast == 2'd3) & (ap_enable_reg_pp0_iter2 == 1'b1)) | ((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln373_reg_1236_pp0_iter1_reg == 1'd0) & (icmp_ln344_reg_1232_pp0_iter1_reg == 1'd0) & (lineStore_1_cast == 2'd3) & (ap_enable_reg_pp0_iter2 == 1'b1)))) begin
        linebuffer_V_3_we0 = 1'b1;
    end else begin
        linebuffer_V_3_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln373_reg_1236_pp0_iter1_reg == 1'd1) & (icmp_ln344_reg_1232_pp0_iter1_reg == 1'd0) & (lineStore_1_cast == 2'd0) & (ap_enable_reg_pp0_iter2 == 1'b1)) | ((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln373_reg_1236_pp0_iter1_reg == 1'd0) & (icmp_ln344_reg_1232_pp0_iter1_reg == 1'd0) & (lineStore_1_cast == 2'd0) & (ap_enable_reg_pp0_iter2 == 1'b1)))) begin
        linebuffer_V_ce0 = 1'b1;
    end else begin
        linebuffer_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        linebuffer_V_ce1 = 1'b1;
    end else begin
        linebuffer_V_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln373_reg_1236_pp0_iter1_reg == 1'd1) & (icmp_ln344_reg_1232_pp0_iter1_reg == 1'd0) & (lineStore_1_cast == 2'd0) & (ap_enable_reg_pp0_iter2 == 1'b1)) | ((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln373_reg_1236_pp0_iter1_reg == 1'd0) & (icmp_ln344_reg_1232_pp0_iter1_reg == 1'd0) & (lineStore_1_cast == 2'd0) & (ap_enable_reg_pp0_iter2 == 1'b1)))) begin
        linebuffer_V_we0 = 1'b1;
    end else begin
        linebuffer_V_we0 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln344_fu_742_p2 = (ap_sig_allocacmp_col_1 + 11'd1);

assign add_ln406_fu_768_p2 = (ap_sig_allocacmp_bram_read_count_load + 12'd1);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

always @ (*) begin
    ap_block_pp0 = ((ap_ST_fsm_pp0_stage0 == ap_CS_fsm) & (1'b1 == ap_block_pp0_stage0_subdone));
end

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_01001 = (((demosaic_out_data241_full_n == 1'b0) & (ap_enable_reg_pp0_iter7 == 1'b1)) | ((ap_predicate_op99_read_state2 == 1'b1) & (gain_out_data240_empty_n == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b1)));
end

always @ (*) begin
    ap_block_pp0_stage0_11001 = (((demosaic_out_data241_full_n == 1'b0) & (ap_enable_reg_pp0_iter7 == 1'b1)) | ((ap_predicate_op99_read_state2 == 1'b1) & (gain_out_data240_empty_n == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b1)));
end

always @ (*) begin
    ap_block_pp0_stage0_11001_ignoreCallOp148 = (((demosaic_out_data241_full_n == 1'b0) & (ap_enable_reg_pp0_iter7 == 1'b1)) | ((ap_predicate_op99_read_state2 == 1'b1) & (gain_out_data240_empty_n == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b1)));
end

always @ (*) begin
    ap_block_pp0_stage0_11001_ignoreCallOp149 = (((demosaic_out_data241_full_n == 1'b0) & (ap_enable_reg_pp0_iter7 == 1'b1)) | ((ap_predicate_op99_read_state2 == 1'b1) & (gain_out_data240_empty_n == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b1)));
end

always @ (*) begin
    ap_block_pp0_stage0_11001_ignoreCallOp150 = (((demosaic_out_data241_full_n == 1'b0) & (ap_enable_reg_pp0_iter7 == 1'b1)) | ((ap_predicate_op99_read_state2 == 1'b1) & (gain_out_data240_empty_n == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b1)));
end

always @ (*) begin
    ap_block_pp0_stage0_11001_ignoreCallOp151 = (((demosaic_out_data241_full_n == 1'b0) & (ap_enable_reg_pp0_iter7 == 1'b1)) | ((ap_predicate_op99_read_state2 == 1'b1) & (gain_out_data240_empty_n == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b1)));
end

always @ (*) begin
    ap_block_pp0_stage0_subdone = (((demosaic_out_data241_full_n == 1'b0) & (ap_enable_reg_pp0_iter7 == 1'b1)) | ((ap_predicate_op99_read_state2 == 1'b1) & (gain_out_data240_empty_n == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b1)));
end

assign ap_block_state1_pp0_stage0_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state1_pp0_stage0_iter0_ignore_call0 = ~(1'b1 == 1'b1);

assign ap_block_state1_pp0_stage0_iter0_ignore_call1 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_state2_pp0_stage0_iter1 = ((ap_predicate_op99_read_state2 == 1'b1) & (gain_out_data240_empty_n == 1'b0));
end

always @ (*) begin
    ap_block_state2_pp0_stage0_iter1_ignore_call0 = ((ap_predicate_op99_read_state2 == 1'b1) & (gain_out_data240_empty_n == 1'b0));
end

always @ (*) begin
    ap_block_state2_pp0_stage0_iter1_ignore_call1 = ((ap_predicate_op99_read_state2 == 1'b1) & (gain_out_data240_empty_n == 1'b0));
end

assign ap_block_state3_pp0_stage0_iter2 = ~(1'b1 == 1'b1);

assign ap_block_state3_pp0_stage0_iter2_ignore_call0 = ~(1'b1 == 1'b1);

assign ap_block_state3_pp0_stage0_iter2_ignore_call1 = ~(1'b1 == 1'b1);

assign ap_block_state4_pp0_stage0_iter3 = ~(1'b1 == 1'b1);

assign ap_block_state4_pp0_stage0_iter3_ignore_call0 = ~(1'b1 == 1'b1);

assign ap_block_state4_pp0_stage0_iter3_ignore_call1 = ~(1'b1 == 1'b1);

assign ap_block_state5_pp0_stage0_iter4 = ~(1'b1 == 1'b1);

assign ap_block_state5_pp0_stage0_iter4_ignore_call0 = ~(1'b1 == 1'b1);

assign ap_block_state5_pp0_stage0_iter4_ignore_call1 = ~(1'b1 == 1'b1);

assign ap_block_state6_pp0_stage0_iter5 = ~(1'b1 == 1'b1);

assign ap_block_state6_pp0_stage0_iter5_ignore_call0 = ~(1'b1 == 1'b1);

assign ap_block_state6_pp0_stage0_iter5_ignore_call1 = ~(1'b1 == 1'b1);

assign ap_block_state7_pp0_stage0_iter6 = ~(1'b1 == 1'b1);

assign ap_block_state7_pp0_stage0_iter6_ignore_call0 = ~(1'b1 == 1'b1);

assign ap_block_state7_pp0_stage0_iter6_ignore_call1 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_state8_pp0_stage0_iter7 = (demosaic_out_data241_full_n == 1'b0);
end

always @ (*) begin
    ap_block_state8_pp0_stage0_iter7_ignore_call0 = (demosaic_out_data241_full_n == 1'b0);
end

always @ (*) begin
    ap_block_state8_pp0_stage0_iter7_ignore_call1 = (demosaic_out_data241_full_n == 1'b0);
end

always @ (*) begin
    ap_condition_238 = ((trunc_ln135_reg_1260_pp0_iter5_reg == 1'd0) & (icmp_ln344_reg_1232_pp0_iter5_reg == 1'd0) & (trunc_ln == 1'd0));
end

always @ (*) begin
    ap_condition_242 = ((trunc_ln135_reg_1260_pp0_iter5_reg == 1'd1) & (icmp_ln344_reg_1232_pp0_iter5_reg == 1'd0) & (trunc_ln == 1'd1));
end

always @ (*) begin
    ap_condition_660 = ((1'b0 == ap_block_pp0_stage0_11001) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0));
end

always @ (*) begin
    ap_condition_662 = ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0));
end

always @ (*) begin
    ap_condition_702 = ((trunc_ln135_reg_1260_pp0_iter5_reg == 1'd1) & (icmp_ln344_reg_1232_pp0_iter5_reg == 1'd0) & (trunc_ln == 1'd0));
end

always @ (*) begin
    ap_condition_704 = ((trunc_ln135_reg_1260_pp0_iter5_reg == 1'd0) & (icmp_ln344_reg_1232_pp0_iter5_reg == 1'd0) & (trunc_ln == 1'd1));
end

always @ (*) begin
    ap_enable_operation_101 = (ap_predicate_op101_load_state2 == 1'b1);
end

always @ (*) begin
    ap_enable_operation_102 = (ap_predicate_op102_load_state2 == 1'b1);
end

always @ (*) begin
    ap_enable_operation_103 = (ap_predicate_op103_load_state2 == 1'b1);
end

always @ (*) begin
    ap_enable_operation_104 = (ap_predicate_op104_load_state2 == 1'b1);
end

always @ (*) begin
    ap_enable_operation_122 = (ap_predicate_op122_store_state3 == 1'b1);
end

always @ (*) begin
    ap_enable_operation_124 = (ap_predicate_op124_store_state3 == 1'b1);
end

always @ (*) begin
    ap_enable_operation_126 = (ap_predicate_op126_store_state3 == 1'b1);
end

always @ (*) begin
    ap_enable_operation_128 = (ap_predicate_op128_store_state3 == 1'b1);
end

always @ (*) begin
    ap_enable_operation_130 = (ap_predicate_op130_store_state3 == 1'b1);
end

always @ (*) begin
    ap_enable_operation_132 = (ap_predicate_op132_store_state3 == 1'b1);
end

always @ (*) begin
    ap_enable_operation_134 = (ap_predicate_op134_store_state3 == 1'b1);
end

always @ (*) begin
    ap_enable_operation_136 = (ap_predicate_op136_store_state3 == 1'b1);
end

always @ (*) begin
    ap_enable_operation_86 = (ap_predicate_op86_load_state1 == 1'b1);
end

always @ (*) begin
    ap_enable_operation_87 = (ap_predicate_op87_load_state1 == 1'b1);
end

always @ (*) begin
    ap_enable_operation_88 = (ap_predicate_op88_load_state1 == 1'b1);
end

always @ (*) begin
    ap_enable_operation_89 = (ap_predicate_op89_load_state1 == 1'b1);
end

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

always @ (*) begin
    ap_enable_state1_pp0_iter0_stage0 = ((ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0));
end

always @ (*) begin
    ap_enable_state2_pp0_iter1_stage0 = ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0));
end

always @ (*) begin
    ap_enable_state3_pp0_iter2_stage0 = ((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0));
end

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign ap_phi_reg_pp0_iter0_b_5_reg_532 = 'bx;

assign ap_phi_reg_pp0_iter0_empty_104_reg_510 = 'bx;

assign ap_phi_reg_pp0_iter0_empty_105_reg_521 = 'bx;

assign ap_phi_reg_pp0_iter0_empty_reg_499 = 'bx;

assign ap_phi_reg_pp0_iter0_g_4_reg_545 = 'bx;

assign ap_phi_reg_pp0_iter0_imgblock_V_14_1_reg_487 = 'bx;

assign ap_phi_reg_pp0_iter0_p_Val2_27_reg_471 = 'bx;

assign ap_phi_reg_pp0_iter0_r_5_reg_558 = 'bx;

always @ (*) begin
    ap_predicate_op101_load_state2 = ((icmp_ln344_reg_1232 == 1'd0) & (icmp_ln373_reg_1236 == 1'd1));
end

always @ (*) begin
    ap_predicate_op102_load_state2 = ((icmp_ln344_reg_1232 == 1'd0) & (icmp_ln373_reg_1236 == 1'd1));
end

always @ (*) begin
    ap_predicate_op103_load_state2 = ((icmp_ln344_reg_1232 == 1'd0) & (icmp_ln373_reg_1236 == 1'd1));
end

always @ (*) begin
    ap_predicate_op104_load_state2 = ((icmp_ln344_reg_1232 == 1'd0) & (icmp_ln373_reg_1236 == 1'd1));
end

always @ (*) begin
    ap_predicate_op122_store_state3 = ((icmp_ln373_reg_1236_pp0_iter1_reg == 1'd0) & (icmp_ln344_reg_1232_pp0_iter1_reg == 1'd0) & (lineStore_1_cast == 2'd2));
end

always @ (*) begin
    ap_predicate_op124_store_state3 = ((icmp_ln373_reg_1236_pp0_iter1_reg == 1'd0) & (icmp_ln344_reg_1232_pp0_iter1_reg == 1'd0) & (lineStore_1_cast == 2'd1));
end

always @ (*) begin
    ap_predicate_op126_store_state3 = ((icmp_ln373_reg_1236_pp0_iter1_reg == 1'd0) & (icmp_ln344_reg_1232_pp0_iter1_reg == 1'd0) & (lineStore_1_cast == 2'd0));
end

always @ (*) begin
    ap_predicate_op128_store_state3 = ((icmp_ln373_reg_1236_pp0_iter1_reg == 1'd0) & (icmp_ln344_reg_1232_pp0_iter1_reg == 1'd0) & (lineStore_1_cast == 2'd3));
end

always @ (*) begin
    ap_predicate_op130_store_state3 = ((icmp_ln373_reg_1236_pp0_iter1_reg == 1'd1) & (icmp_ln344_reg_1232_pp0_iter1_reg == 1'd0) & (lineStore_1_cast == 2'd2));
end

always @ (*) begin
    ap_predicate_op132_store_state3 = ((icmp_ln373_reg_1236_pp0_iter1_reg == 1'd1) & (icmp_ln344_reg_1232_pp0_iter1_reg == 1'd0) & (lineStore_1_cast == 2'd1));
end

always @ (*) begin
    ap_predicate_op134_store_state3 = ((icmp_ln373_reg_1236_pp0_iter1_reg == 1'd1) & (icmp_ln344_reg_1232_pp0_iter1_reg == 1'd0) & (lineStore_1_cast == 2'd0));
end

always @ (*) begin
    ap_predicate_op136_store_state3 = ((icmp_ln373_reg_1236_pp0_iter1_reg == 1'd1) & (icmp_ln344_reg_1232_pp0_iter1_reg == 1'd0) & (lineStore_1_cast == 2'd3));
end

always @ (*) begin
    ap_predicate_op148_call_state3 = ((trunc_ln135_reg_1260_pp0_iter1_reg == 1'd0) & (icmp_ln344_reg_1232_pp0_iter1_reg == 1'd0) & (trunc_ln == 1'd0));
end

always @ (*) begin
    ap_predicate_op149_call_state3 = ((trunc_ln135_reg_1260_pp0_iter1_reg == 1'd0) & (icmp_ln344_reg_1232_pp0_iter1_reg == 1'd0) & (trunc_ln == 1'd0));
end

always @ (*) begin
    ap_predicate_op150_call_state3 = ((trunc_ln135_reg_1260_pp0_iter1_reg == 1'd1) & (icmp_ln344_reg_1232_pp0_iter1_reg == 1'd0) & (trunc_ln == 1'd0));
end

always @ (*) begin
    ap_predicate_op151_call_state3 = ((trunc_ln135_reg_1260_pp0_iter1_reg == 1'd1) & (icmp_ln344_reg_1232_pp0_iter1_reg == 1'd0) & (trunc_ln == 1'd0));
end

always @ (*) begin
    ap_predicate_op152_call_state3 = ((trunc_ln135_reg_1260_pp0_iter1_reg == 1'd0) & (icmp_ln344_reg_1232_pp0_iter1_reg == 1'd0) & (trunc_ln == 1'd1));
end

always @ (*) begin
    ap_predicate_op153_call_state3 = ((trunc_ln135_reg_1260_pp0_iter1_reg == 1'd0) & (icmp_ln344_reg_1232_pp0_iter1_reg == 1'd0) & (trunc_ln == 1'd1));
end

always @ (*) begin
    ap_predicate_op154_call_state3 = ((trunc_ln135_reg_1260_pp0_iter1_reg == 1'd1) & (icmp_ln344_reg_1232_pp0_iter1_reg == 1'd0) & (trunc_ln == 1'd1));
end

always @ (*) begin
    ap_predicate_op155_call_state3 = ((trunc_ln135_reg_1260_pp0_iter1_reg == 1'd1) & (icmp_ln344_reg_1232_pp0_iter1_reg == 1'd0) & (trunc_ln == 1'd1));
end

always @ (*) begin
    ap_predicate_op86_load_state1 = ((icmp_ln344_fu_736_p2 == 1'd0) & (icmp_ln373_fu_748_p2 == 1'd1));
end

always @ (*) begin
    ap_predicate_op87_load_state1 = ((icmp_ln344_fu_736_p2 == 1'd0) & (icmp_ln373_fu_748_p2 == 1'd1));
end

always @ (*) begin
    ap_predicate_op88_load_state1 = ((icmp_ln344_fu_736_p2 == 1'd0) & (icmp_ln373_fu_748_p2 == 1'd1));
end

always @ (*) begin
    ap_predicate_op89_load_state1 = ((icmp_ln344_fu_736_p2 == 1'd0) & (icmp_ln373_fu_748_p2 == 1'd1));
end

always @ (*) begin
    ap_predicate_op99_read_state2 = ((cmp162 == 1'd1) & (icmp_ln344_reg_1232 == 1'd0));
end

assign cmp162_read_read_fu_204_p2 = cmp162;

assign demosaic_out_data241_din = {{{select_ln40_2_fu_1060_p3}, {select_ln40_1_fu_1032_p3}}, {select_ln40_fu_1004_p3}};

assign icmp_ln344_fu_736_p2 = ((ap_sig_allocacmp_col_1 == p_read1) ? 1'b1 : 1'b0);

assign icmp_ln373_fu_748_p2 = (($signed(zext_ln344_1_fu_732_p1) < $signed(sub219)) ? 1'b1 : 1'b0);

assign icmp_ln40_1_fu_1022_p2 = ((tmp_47_fu_1012_p4 != 3'd0) ? 1'b1 : 1'b0);

assign icmp_ln40_2_fu_1050_p2 = ((tmp_48_fu_1040_p4 != 3'd0) ? 1'b1 : 1'b0);

assign icmp_ln40_fu_994_p2 = ((tmp_fu_984_p4 != 3'd0) ? 1'b1 : 1'b0);

assign imgblock_V_12_out = imgblock_V_5_fu_176;

assign imgblock_V_5_out = imgblock_V_3_fu_168;

assign imgblock_V_8_out = imgblock_V_4_fu_172;

assign imgblock_V_9_out = imgblock_V_12_reg_1295_pp0_iter5_reg;

assign linebuffer_V_1_address0 = zext_ln344_fu_870_p1;

assign linebuffer_V_1_address1 = zext_ln344_2_fu_757_p1;

assign linebuffer_V_1_d0 = ap_phi_reg_pp0_iter2_p_Val2_27_reg_471;

assign linebuffer_V_2_address0 = zext_ln344_fu_870_p1;

assign linebuffer_V_2_address1 = zext_ln344_2_fu_757_p1;

assign linebuffer_V_2_d0 = ap_phi_reg_pp0_iter2_p_Val2_27_reg_471;

assign linebuffer_V_3_address0 = zext_ln344_fu_870_p1;

assign linebuffer_V_3_address1 = zext_ln344_2_fu_757_p1;

assign linebuffer_V_3_d0 = ap_phi_reg_pp0_iter2_p_Val2_27_reg_471;

assign linebuffer_V_address0 = zext_ln344_fu_870_p1;

assign linebuffer_V_address1 = zext_ln344_2_fu_757_p1;

assign linebuffer_V_d0 = ap_phi_reg_pp0_iter2_p_Val2_27_reg_471;

assign select_ln40_1_fu_1032_p3 = ((icmp_ln40_1_fu_1022_p2[0:0] == 1'b1) ? 10'd1023 : trunc_ln260_3_fu_1028_p1);

assign select_ln40_2_fu_1060_p3 = ((icmp_ln40_2_fu_1050_p2[0:0] == 1'b1) ? 10'd1023 : trunc_ln260_4_fu_1056_p1);

assign select_ln40_fu_1004_p3 = ((icmp_ln40_fu_994_p2[0:0] == 1'b1) ? 10'd1023 : trunc_ln260_fu_1000_p1);

assign tmp_47_fu_1012_p4 = {{ap_phi_reg_pp0_iter7_g_4_reg_545[12:10]}};

assign tmp_48_fu_1040_p4 = {{ap_phi_reg_pp0_iter7_r_5_reg_558[12:10]}};

assign tmp_fu_984_p4 = {{ap_phi_reg_pp0_iter7_b_5_reg_532[12:10]}};

assign trunc_ln135_fu_774_p1 = ap_sig_allocacmp_col_1[0:0];

assign trunc_ln260_3_fu_1028_p1 = ap_phi_reg_pp0_iter7_g_4_reg_545[9:0];

assign trunc_ln260_4_fu_1056_p1 = ap_phi_reg_pp0_iter7_r_5_reg_558[9:0];

assign trunc_ln260_fu_1000_p1 = ap_phi_reg_pp0_iter7_b_5_reg_532[9:0];

assign zext_ln124_fu_981_p1 = r_3_reg_1302_pp0_iter5_reg;

assign zext_ln344_1_fu_732_p1 = ap_sig_allocacmp_col_1;

assign zext_ln344_2_fu_757_p1 = ap_sig_allocacmp_bram_read_count_load_1;

assign zext_ln344_fu_870_p1 = col_1_reg_1227_pp0_iter1_reg;

endmodule //ISPPipeline_accel_demosaicing_3_13_17_1080_1920_1_false_Pipeline_Col_Loop
